### ISSUE TITLE
Search/Filter Template 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#1011]
Searching and filtering of items in Lists and Tables, since choosing what to show is different than how we show it.

### Deliverables

- published Figma designs showing variations.

### User Tasks

Recommend starting by thinking about tasks users might want to accomplish.

- quickly finding one thing from a large set, needle in a haystack, user might know a name/id or might not. If not, maybe she knows something about it (filter) but then will want to scan to locate it
- exploring aggregate information about multiple items, for example: how many items are in a particular state or at a particular version, or combination of multiple factors

### Aspects

- scenarios where 80% of the time the user will likely search and/or vs. rarely
- one or two filter choices are frequently used but others much less frequently
- many possible values to filter for a particular attribute
- multiple values for an attribute

**Comment by gregfuruiye** [comment]
I'd like to close this issue so we can split search and filter. The exploration for search on data table is complete. I'll be creating new cards for search on list and cards, then another card for continuing filter on table.

**Comment by gregfuruiye** [comment]
Search for table is complete and noted in Table Guidance:
https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table-Component?node-id=546%3A16935

**Comment by gregfuruiye** [comment]
Search on a list/card is continuing exploration #1035 
Filter list/card is continued #1037 
Filter table is continued #1036
