### ISSUE TITLE
Establish Best Practice for Table Sort Keyboard Navigation 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#1012]
This issue is created to work through the sort function within the basic table designs and establish a "best practice" for keyboard navigation. 
https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table-Component?node-id=381%3A9

**Comment by ericsoderberghp** [comment]
Subsumed by https://github.com/hpe-design/design-system/issues/1013
