### ISSUE TITLE
Table column grouping

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#1015]
Explore how to handle grouping of table columns.

One strategy would be to add an additional header row and use `colspan` for group cell labels. How would this look visually? How would column resizing be affected?

Another strategy could be a single header row with a prefix on the first column and vertical dividers between the grouped columns, since we don't have vertical column dividers currently.

Perhaps other approaches?

https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table-Component?node-id=546%3A16952

**Comment by gregfuruiye** [comment]
Here's the specific Figma frame that begins to explore some ideas. In most cases, an effort to maintain a single line header is appropriate:

https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table-Component?node-id=663%3A1013

**Comment by gregfuruiye** [comment]
I've completed a recommendation regarding table column grouping. Essentially, don't do it :)

https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table-Component?node-id=485%3A0
