### ISSUE TITLE
Single select + multi-select of checkboxes on a table

### ISSUE THREAD

**Issue by vavalos5** [hpe-design/design-system#1021]

**Comment by vavalos5** [comment]
Goal:
Describe how Tables can be interacted with using only a keyboard.

- [ ] enabled behavior 
- [ ] hover behavior
- [ ] focused behavior
- [ ] batched items

Deliverables
publish an Accessibility section on the Table page describing how keyboard interaction works.

It should be easy to tab through a page without having to progress through every row in a table. To achieve that, expect that the table body receives and indicates focus while the arrow keys permit traversing rows with an indicator showing the current position, similar to List, Select, Menu, TextInput suggestions, etc.

**Comment by vavalos5** [comment]
After doing some research on batched items on a table, I found it hard to come by any kind of information. I don't think we'd want to limit teams from being able to single/multi select items the way they want to depending on their use case. After discussing with Matt, we both felt that we won't be touching on that for guidance.

**Comment by ericsoderberghp** [comment]
Will we have anything that demonstrates at least one approach? Or, will be leaving it for teams to figure it out on their own? I'm fine with not being overly restrictive, but I think an example to follow would be helpful.

**Comment by vavalos5** [comment]
Great question! I do have an example on the Figma file i'm working on where I show a few checkboxes that have been selected with an action button on the top right corner of the table. However, it doesn't go any further than though (like selection the action button and performing an action) to avoid confusion. 

Excuse my run on sentences 👍

**Comment by ericsoderberghp** [comment]
I think I'm more interested in how the selection is managed than in what is ultimately done with it.

Do we show how many items are selected, in case some aren't visible due to scrolling or pagination?

Do we have an example that includes "select all" and "clear selection" interaction?

Is the selection affected by subsequent searching, filtering, or pagination interaction?

**Comment by vavalos5** [comment]
Great ideas! I think there may have to be some type of exploration on showing the amount of items that have been selected and how to show that on a table. I say this because of the real estate a table already takes, but I do think this is a great idea!

For "select all" or clear selection" I think the  checkbox at the header level would be able to perform this action.

Selections should not be affect by searched/filter items or pagination. I think if we're going to be showing the number of selected items above the table, this should give a clear indication that there are other items selected, even if the user has filtered/searched or moved on to another page. 

I'll continue to work on these. Thanks for the feedback Eric!

**Comment by vavalos5** [comment]
Greg and I discussed a bit on how search/filter could affect selected items. He mentioned he would work on that part, but to move this ticket forward, I will be including a reserved area above the table where types of actions + indicators ( search, filter, # of selected items) would live.

**Comment by vavalos5** [comment]
Some small guidance/visual on batched items:
https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table-Component?node-id=546%3A16935
