### ISSUE TITLE
Table keyboard interaction for rows

### ISSUE THREAD

**Issue by vavalos5** [hpe-design/design-system#1022]

**Comment by vavalos5** [comment]
**Goal:** 
Describe how Tables can be interacted with using only a keyboard.

**Deliverables**
publish an Accessibility section on the Table page describing how keyboard interaction works.

when entire rows are clickable, how to traverse rows and "click" them
when rows aren't clickable but cells have controls on them
where any focus indicator is placed
where any sub-focus indicator is placed

It should be easy to tab through a page without having to progress through every row in a table. To achieve that, expect that the table body receives and indicates focus while the arrow keys permit traversing rows with an indicator showing the current position, similar to List, Select, Menu, TextInput suggestions, etc.

**Comment by vavalos5** [comment]
This Figma file is related to this ticket: https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table-Component?node-id=623%3A1439

**Comment by ericsoderberghp** [comment]
> - In the scenario where a row has 0-1 interactive elements, use infinteScroll.

I think infinite scroll vs. pagination should be independent of row interaction.

**Comment by ericsoderberghp** [comment]
> A row with 0-1 interactive elements:

**Comment by ericsoderberghp** [comment]
I am appreciating the level of detail in the Figma designs :)

**Comment by ericsoderberghp** [comment]
> Enter: Enter is used to perform the row’s action

I think we should mention that pressing the Enter key should trigger the same behavior as using the mouse to click on the row.

**Comment by ericsoderberghp** [comment]
I think we should include an example where selection is performed by clicking anywhere in the row but is indicated via a checkbox in the first column. In other words, I don't think we need to have cell-level interaction to support selection.

**Comment by ericsoderberghp** [comment]
> If nothing on a table is selectable or has no interactivity (but the table header),
does the entire table recieve a focus state? Then are up & down arrows included?

If there is no interactivity in the table, then there is no focus state. Screen readers already provide a means of traversing a table to read its contents.

**Comment by ericsoderberghp** [comment]
> Should screen readers read everything that’s in a row? Even it’s not interactive?

I believe they already know how to do this.

**Comment by vavalos5** [comment]
> ld include an example where selection is performed by clicking anywhere in the row but is indicated via a checkbox in the first column. In other words, I don't think we need to have cell-l

I think i'm a little confused on this comment. I get what you mean about making an entire row interactive to perform a selection. However, the example I have on Figma shows that there is also some type of affordance on some of the text to right of the checkboxes, indicating that the text is selectable. Would the row still perform a selection even if it has other interactive elements? If so, would each interactive element still receive a focus behavior when using tab?

**Comment by ericsoderberghp** [comment]
When there are no interactive elements in the cells but selection is desired, then I think the interaction would work at a row level, click the row toggles selection, tab focuses on table body, arrows move up and down rows, space or enter toggles selection. CheckBox in first column is not interactive itself, it is just a selection indicator.

When there are interactive elements within the cells, the CheckBox in the first column is interactive and can be reached via tab, just like the other interactive elements.

**Comment by vavalos5** [comment]
Ah, gotcha! So, I can keep the examples I currently have, but just add the interactive row level selection, correct? Just want to confirm 😄

**Comment by vavalos5** [comment]
@ericsoderberghp I've implemented the examples as discussed. Ready for another review 😃 
https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table-Component?node-id=628%3A24956

**Comment by ericsoderberghp** [comment]
> > A row with 0-1 interactive elements:
> 
> I think we should differentiate on whether a row **is** interactive or whether a cell within the row **contains** an interactive element.

I think we still need to improve the language here.

**Comment by ericsoderberghp** [comment]
> Table Cells Keyboard Behaviors

I'm not sure what this means as a heading. Should it be "Table Rows Keyboard Behaviors"?

**Comment by ericsoderberghp** [comment]
I don't think the header interaction is different between the two scenarios of row interaction vs. cell interaction. I think we could have one section for header interaction, one section for body row interaction, and one for body cell interaction.

**Comment by ericsoderberghp** [comment]
Good job on the mouse and keyboard interaction at the row level when making selections. 👍

**Comment by vavalos5** [comment]
> I don't think the header interaction is different between the two scenarios of row interaction vs. cell interaction. I think we could have one section for header interaction, one section for body row interaction, and one for body cell interaction.

I condensed this a tiny bit. I know some of the steps seem a bit redundant, however, I wanted to be thorough as there's so many behaviors. It can be easy to mistaken a behavior or step. Also, since both scenarios are ever so slightly different.

**Comment by vavalos5** [comment]
> > > A row with 0-1 interactive elements:
> > 
> > 
> > I think we should differentiate on whether a row **is** interactive or whether a cell within the row **contains** an interactive element.
> 
> I think we still need to improve the language here.

I could use help with this :) Any suggestions on how I can improve this?
