### ISSUE TITLE
Update theme with heading and text t-shirt sizing

### ISSUE THREAD

**Issue by gregfuruiye** [hpe-design/design-system#1025]
Figma File and styles are shown here:
https://www.figma.com/file/oJhw3JqMemtbwWjlLPWW5O/HPE-Typography-Styles?node-id=0%3A1[https://www.figma.com/file/oJhw3JqMemtbwWjlLPWW5O/HPE-Typography-Styles?node-id=0%3A1](url)

**Comment by halocline** [comment]
Audited w/ Greg - Theme checked out
