### ISSUE TITLE
Search on List/Cards

### ISSUE THREAD

**Issue by gregfuruiye** [hpe-design/design-system#1035]
Guidance and examples for search on list and cards

Figma File WIP page:
https://www.figma.com/file/ChTUhUi0PiDCJ5V6iAYw5p/HPE-Search-Templates?node-id=1%3A9

**Comment by gregfuruiye** [comment]
After a brief session with @halocline:

- Search should be defined as when the user is looking to locate something specific
- Search component enables the search pattern/behavior
- Consider a 'Patterns' section, subsection of a component, or is it within 'template' ?
- Search as a pattern will have examples with list, cards, table

**Comment by ericsoderberghp** [comment]
How about a 'Search' template that has examples with Table, List, Card?

I'm reluctant to add a 'Patterns' section as it seems too similar to 'Templates', unless we were to rename 'Templates' to 'Patterns'.

**Comment by gregfuruiye** [comment]
I can go with that, I'm still struggling with what 'template' really means for us, though. When looking at other ways people are talking about these kinds of things, it seems that search and filter both fall into patterns or behaviors rather than people using a term like template. I don't really have a strong opinion, so we'll go with a search 'template'

**Comment by gregfuruiye** [comment]
Added some more resources and use case visualizations from other teams. Included a set of recommendations for search to integrate into the component documenation:
https://www.figma.com/file/ChTUhUi0PiDCJ5V6iAYw5p/HPE-Search-Templates?node-id=1%3A12

Visualizations went through a bigger iteration and updated:
https://www.figma.com/file/ChTUhUi0PiDCJ5V6iAYw5p/HPE-Search-Templates?node-id=1%3A9
