### ISSUE TITLE
Audit the Philosophy and Principles page in order to align with Brand Strategy 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#1040]
We need to evaluate the [Brand Strategy](https://h10014.www1.hpe.com/brand-central/content/brand-strategy) page and make any updates deemed necessary to the [Philosophy and Principles](https://design-system.hpe.design/foundation/philosophy-and-principles) page to show alignment with the HPE Brand.

**Comment by cherih** [comment]
@mikew and @ericsoderberghp  - From my perspective, this page appears to be aligned with the Brand Strategy, including essence, voice, etc. I would like to add simple copy to the page, making this claim and including a link to the Brand Strategy page, if more information is needed.

However, I haven't consulted with anyone from Brand Central about this. 

Do we need to talk to someone in Brand Central before adding the claim of alignment? Or add the claim and get input afterward?

Who can I talk to in Brand Central about reviewing the page for alignment with the Brand Strategy?

**Comment by MikeWalrath** [comment]
@cherih no worries. Lets incorporate your proposal with the link and I can take it from there. I will review it with the Brand team and ask if they would like to make any additional edits. With the high level agreement from Brand I dont believe they will have an issue with it.

**Comment by cherih** [comment]
Propose adding this claim at the top of the DS Philosophy and Principles page, right under the first sentence:

The HPE Design System philosophy and principles are aligned with the HPE brand strategy. For more information about this strategy, go to the [Brand Strategy](https://h10014.www1.hpe.com/brand-central/content/brand-strategy) page on Brand Central.
