### ISSUE TITLE
Color status-critical mismatch between the DS theme and website

### ISSUE THREAD

**Issue by ShimiSun** [hpe-design/design-system#1059]
### Is this issue related to the design system core library or design system website?
design system website

### Expected Behavior
Currently, the DS theme is pointing to a specific dark/light color, while the website is pointing to the red color for status-critical, which one is the correct color?

### Actual Behavior
Mismatch and uncertainty which color has the correct reference.

### URL, screen shot, or CodeSandbox exhibiting the issue
![image](https://user-images.githubusercontent.com/6320236/90712218-d154fd80-e25f-11ea-9c1d-9cfceab796ce.png)

### Steps to Reproduce

Compare https://github.com/grommet/grommet-theme-hpe/blob/NEXT/src/js/index.js#L81
with https://design-system.hpe.design/foundation/color

### Your Environment

- Design System version: NA, NEXT stable theme
- Grommet version: stable
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by taysea** [comment]
Here is the issue that updates `status-critical` in the theme: https://github.com/hpe-design/design-system/issues/989, we can update the site to match
