### ISSUE TITLE
Nav - Refactor to new designs, leverage new grommet component and decouple from aries-site Header

### ISSUE THREAD

**Issue by ShimiSun** [hpe-design/design-system#108]
The decoupling of Nav from Header was addressed on recent PR, but there is still more work refactoring to address the new designs.

**Comment by MikeWalrath** [comment]
Is there any additional work here?

**Comment by taysea** [comment]
The decoupling is done. In terms of what "Nav" is, we are not currently using Nav in aries-site at all. Based on a previous server call, it seems like "Nav" would be a grommet component that only could contain anchors or buttons potentially?

I think in terms of immediate tasks on this, they've been completed and this can be closed.

What remains as potentially follow-up would be discussions about how this component might be used in Server app, if it's just imported from grommet, etc.

**Comment by ShimiSun** [comment]
I think this issue is more about the Nav component on aries-core. The Nav on the core library isn't using the Grommet Nav, and it performs as a NavBar rather than a Nav so renaming should be considered.

**Comment by halocline** [comment]
Has been implemented in Carte version of site.
