### ISSUE TITLE
Table header/footer/column pinning

### ISSUE THREAD

**Issue by ericsoderberghp** [hpe-design/design-system#1087]
Enhance the design resources for Table to include how the header, footer, and/or columns can be pinned such that do not move when scrolling the body of the table. Of particular note is any styling direction on their background when the table body is scrolling under them. For instance, is there just a bit of opacity to help convey what is happening?

For header and footer pinning, the table body scrolls vertically underneath them. The height of the overall Table can be tied to the available vertical real-estate.

For column pinning, the rest of the table scrolls horizontally underneath the pinned column. The horizontal real-estate is likely driven by the available space.

See https://storybook.grommet.io/?path=/story/datatable--fill-and-pin and experiment with changing the size of the browser window and then scrolling.

**Comment by vavalos5** [comment]
Figma file: https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table-Component?node-id=1341%3A0

**Comment by vavalos5** [comment]
After some explorations, we decided on option 10 in the Figma file
