### ISSUE TITLE
Add guidance and for filled icons 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#1097]
We would like to avoid confusion between filled and open icons. If we could provide guidance and examples it would bring clarity for our designers.

**Comment by gregfuruiye** [comment]
Filled status icons have been added to the icons Figma file and assets library

https://www.figma.com/file/G99KGffGLFKICy8xRs51lW/HPE-Icons?node-id=261%3A0

**Comment by gregfuruiye** [comment]
Added some text to the icons page for using filled status icons.

https://www.figma.com/file/G99KGffGLFKICy8xRs51lW/HPE-Icons?node-id=582%3A6
