### ISSUE TITLE
Table - Units in header cells

### ISSUE THREAD

**Issue by halocline** [hpe-design/design-system#1108]
[From Slack](https://hpe.slack.com/archives/GPPLUK6LR/p1599171792004400?thread_ts=1599059119.000900&cid=GPPLUK6LR)

agreed with Greg’s comment about deciding whether to put units in the header or body cells, I can see arguments for each, might be a good quick-research topic

- [x] Update units in examples to be in headers
- [x] Get review/feedback ([Preview](https://deploy-preview-1089--keen-mayer-a86c8b.netlify.app/components/table))
- [x] Decide on need for research and create issue

**Comment by halocline** [comment]
@vavalos5 or @gregfuruiye - Would either of you be able to take a look at the modified column headers, which move unit labels from data to column header? Please provide any adjustments you'd like to be made and whether this needs/deserves additional research.

[Preview](https://deploy-preview-1089--keen-mayer-a86c8b.netlify.app/components/table)

**Comment by vavalos5** [comment]
I think this looks good Matt. There is a ticket in the backlog #1101 which Raja was going to start working on. I think it would be worth doing some small researching to back this up. @gregfuruiye What do you think? 🤔

**Comment by gregfuruiye** [comment]
Here is @rajasekar-ramasamy designs for handling units in header cells:

https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table-Component?node-id=1519%3A8

**Comment by halocline** [comment]
@rajasekar-ramasamy I have implemented the units in header cell designs. Can you confirm they align to your expectations?

[Preview](https://deploy-preview-1089--keen-mayer-a86c8b.netlify.app/components/table)

Related https://github.com/hpe-design/design-system/issues/1101
