### ISSUE TITLE
Table - Apply filter label summary

### ISSUE THREAD

**Issue by halocline** [hpe-design/design-system#1111]
[From Slack](https://hpe.slack.com/archives/GPPLUK6LR/p1599171792004400?thread_ts=1599059119.000900&cid=GPPLUK6LR)

“Selecting multiple records & batch actions” would benefit from a summary label confirming how many are selected.

- [x] Apply filter summarization to example

**Comment by halocline** [comment]
@gregfuruiye @rajasekar-ramasamy -- Related to https://github.com/hpe-design/design-system/issues/1086

I have incorporated a selection summary in the "Manage Orders" example. Implemented the following:
- If nothing selected, do not display summary
- If selected items, display summary
- Adjusted summary text to read "X of Y items selected"

Please take a look and see if there are adjustments we want to make.

[Preview](https://deploy-preview-1089--keen-mayer-a86c8b.netlify.app/components/table#selecting-multiple-records-and-batch-actions)

**Comment by gregfuruiye** [comment]
In our filter examples, we're showing the total number of items even when something is not selected/filtered/searched. So the summary would read, "**12** items"

Let's add that into the example. Let me know if there are concerns or questions.

**Comment by halocline** [comment]
> In our filter examples, we're showing the total number of items even when something is not selected/filtered/searched. So the summary would read, "**12** items"
> 
> I started an exploration on this here:
> https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table-Component?node-id=920%3A142510
> 
> Let's add that into the example. Let me know if there are concerns or questions.

So, regardless of "selectability," should we always be displaying the total item/record count? Said another way, should tables always have a total item count? Or is the total item count applicable when multi-select or filter controls are present?

**Comment by gregfuruiye** [comment]
There's no real prescription here, but it is an option. In the use cases we have as example from other teams, the item count is not included. However, many of our use cases include 100's or even 1000's of items. It's helpful to know how large a thing is so I can make decisions about scrolling, searching, filtering...

I could also anticipate when there are 1000's of things and yet the UI may only load 200 at a time to address efficiency and infinite scroll behavior, the item count may not reflect the truth. Therefore, a team may elect to not show the total item count unless it is truly known. 

Visually, it fills the spacing between the title and table without making the layout feeling disassociated. And if you inserted it causing the table to 'drop' making space for the selection count when a selection is made, that seems awkward.

I'm sticking with keeping the full item count, but its not a hill I'll die on :)
