### ISSUE TITLE
Navigating search results with down arrow should scroll

### ISSUE THREAD

**Issue by karatechops** [hpe-design/design-system#192]
With the search component open, if the user hits the down arrow to navigate results they can navigate outside of the component viewport. When the user navigates past the component's viewport the scroll position should be updated so that the active entry is visible.

![](http://g.recordit.co/rGd5Yok9XO.gif)

**Comment by taysea** [comment]
Agreed. This is a grommet bug with how suggestions drop is rendered. I had peeked at it a couple weeks ago but wasn't able to resolve it yet. Ideally, we could transfer the functionality of Select suggestions to TextInput suggestions since this functionality is already working in Select.

**Comment by taysea** [comment]
Will be resolved by: https://github.com/grommet/grommet/pull/3703
