### ISSUE TITLE
Routing Pages - Design, Develop, Resources

### ISSUE THREAD

**Issue by taysea** [hpe-design/design-system#194]
Each of these topics needs a page like the screenshot below. For each of these pages, we need:
- Name
- Icon
- Description

<img width="445" alt="Screen Shot 2020-01-13 at 1 30 20 PM" src="https://user-images.githubusercontent.com/12522275/72293824-274a2e80-3609-11ea-95d8-906b324f2129.png">

**Comment by MikeWalrath** [comment]
@taysea is this still relevant?

**Comment by taysea** [comment]
Content has been provided for these. Closing now.
