### ISSUE TITLE
Masked input control doesn't close on click outside menu

### ISSUE THREAD

**Issue by bryanjacquot** [hpe-design/design-system#272]
When a menu is open as shown in the following screen, clicking outside the menu, or in the next control doesn't close the former.  This makes for a fun challenge in getting them to close again.

![image](https://user-images.githubusercontent.com/6393696/72852449-c6a39d00-3c6b-11ea-9b06-ded3a5ec02f5.png)

**Comment by ericsoderberghp** [comment]
I believe this has been fixed already. Can someone verify?

**Comment by taysea** [comment]
Yes, this has been resolved. I am closing this issue.
