### ISSUE TITLE
Form fields use a design style that research showed doesn't work as well as fields with boxes / outlines

### ISSUE THREAD

**Issue by bryanjacquot** [hpe-design/design-system#274]
![image](https://user-images.githubusercontent.com/6393696/72852587-40d42180-3c6c-11ea-86b1-497025dc6eea.png)

https://medium.com/google-design/the-evolution-of-material-designs-text-fields-603688b3fe03

Google Material design did research with 550 participants to find the boxes/outlines around form fields tested better than those with just an underline affordance.

**Comment by gregfuruiye** [comment]
I've updated the design here:
https://www.figma.com/file/iXWcXa3QtXAGHnXZnONnty/hpe-design-system?node-id=149%3A107

Here's a screen shot:
<img width="403" alt="Screen Shot 2020-01-23 at 2 26 27 PM" src="https://user-images.githubusercontent.com/17889451/73025324-9e8f7780-3dec-11ea-9c48-a618cef79424.png">

**Comment by ShimiSun** [comment]
@MikeWalrath let's discuss this Form on our grommet staff call.
Currently, grommet out of the box behavior is using the underline rather than the full field border.

**Comment by ericsoderberghp** [comment]
I think we should allow minimal forms, for something like login screens, that label the field via a placeholder, but also have more explicitly labelled fields for forms with more fields.

**Comment by gregfuruiye** [comment]
I agree with Eric. I'm going to run a quick study in UserZoom on simple forms for us using these two use cases. We will be able to measure task completion and task time to completion, as well as task success rates based on the design. I'll look at the research that Bryan referred to as well.

**Comment by ericsoderberghp** [comment]
Some other form exploration: https://designer.grommet.io/?id=forms-eric-soderberg-hpe-com

**Comment by gregfuruiye** [comment]
Here is another older, but an insightful article that focused on eye tracking and focus time: https://www.uxmatters.com/mt/archives/2006/07/label-placement-in-forms.php

From the google research and other research, I think we can possibly put a stake in the ground with a single form design. This may help simplify our storybook, as well as avoid ambiguity while still meeting clear accessibility guidelines.

Labels top and left-aligned, rounded fields, transparent fill, 3:1 color contrast on field borders.

**Comment by gregfuruiye** [comment]
Fields have been updated for a more consistent design. I'll work a quick review for us to align, but they're in Figma now:

https://www.figma.com/file/iXWcXa3QtXAGHnXZnONnty/hpe-design-system?node-id=149%3A107

**Comment by ericsoderberghp** [comment]
good start. I think we still need detail on how validation errors and help text are handled

**Comment by gregfuruiye** [comment]
Yes, Scott Oja has started a document that discusses these very issues. We will be meeting over these this week.

**Comment by halocline** [comment]
@MikeWalrath Do you think this issue is still open? Or can it be closed with the form patterns which are being implemented?

**Comment by MikeWalrath** [comment]
It can be closed with the work being implemented.
