### ISSUE TITLE
Update any references of Aries to HPE Design System

### ISSUE THREAD

**Issue by karatechops** [hpe-design/design-system#286]
- [x] Check canonical meta tags
- [x] Update repo names
- [x] Update URL
- [ ] ~~Consider NPM publishing name (discussion)~~  --- Moved to own issue: https://github.com/hpe-design/design-system/issues/296
- [x] Update Slack channel title

**Comment by halocline** [comment]
Created https://github.com/hpe-design/design-system/issues/296 for NPM naming discussion
