### ISSUE TITLE
Search results click-through not functioning

### ISSUE THREAD

**Issue by halocline** [hpe-design/design-system#292]
![Kapture 2020-01-24 at 9 20 15](https://user-images.githubusercontent.com/1756948/73085277-abaf7380-3e8b-11ea-8d7b-0de65324c1c7.gif)

![Screen Shot 2020-01-24 at 12 25 43 PM](https://user-images.githubusercontent.com/1756948/73099503-e4117a80-3ea8-11ea-8c3a-554d7ca68a8d.png)

**Comment by halocline** [comment]
Trouble shooting notes:

- Initially, I tried to find an Aries commit which introduced this bug. Unsuccessfully.
- Went to commits 1+ week ago when we definitively knew the Search was functioning, but the issue persisted.
- Started thinking dependencies...
  - Pointed to Grommet v2.9.0 (instead of grommet/stable) as issue went away
  - Pointed to Grommet v2.10.0 and issue returned

Steps taken:
- Updated package.json to point to Grommet v2.9.0
- Logged Grommet issue here:

**Comment by ShimiSun** [comment]
>Logged Grommet issue here:

Can you share the link?

**Comment by halocline** [comment]
> > Logged Grommet issue here:
> 
> Can you share the link?

Sorry, in the middle of creating the issue. Wanted to recreate in CodeSandbox, before logging issue. I can log now with the information I currently have, and add in CodeSandbox later if you prefer. Let me know.

**Comment by ShimiSun** [comment]
Just checked all grommet TextInput storybook examples, looks good to me. https://storybook.grommet.io/?path=/story/textinput--custom
If it is a grommet issue we should add a test/storybook example that covers this scenario.

**Comment by halocline** [comment]
https://github.com/grommet/grommet/pull/3699 resolves this issue.
