### ISSUE TITLE
FireFox - Search Input placeholder text illegible

### ISSUE THREAD

**Issue by halocline** [hpe-design/design-system#293]
![Screen Shot 2020-01-24 at 12 02 53 PM](https://user-images.githubusercontent.com/1756948/73096244-96454400-3ea1-11ea-84c7-c239f929e38d.png)

**Comment by ericsoderberghp** [comment]
<img width="1106" alt="Screen Shot 2020-01-31 at 1 26 22 PM" src="https://user-images.githubusercontent.com/11637956/73575588-6364f800-442d-11ea-9526-d05e650b17ec.png">

seems to be working OK for me

**Comment by halocline** [comment]
Confirming that this is working as expected. Issue was reported when pointing to Grommet v2.9.0 (which was put in place while work on https://github.com/hpe-design/design-system/issues/292 was being completed).
