### ISSUE TITLE
Optimize Build Process

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#301]
Ensure that we are using our Netlify build time as effectively as possible

**Comment by halocline** [comment]
One opportunity:
https://github.com/zeit/next.js/blob/master/errors/no-cache.md

**Comment by halocline** [comment]
https://community.netlify.com/t/common-issue-how-can-i-optimize-my-netlify-build-time/3907

**Comment by halocline** [comment]
**Approach**
Looking at optimizing the "build" process in three areas:

1. Prior to build (i.e. catch issues earlier in the development process)
  - Check Grommet/stable version in Yarn.lock, update if newer commits
  - Run tests
    - Jest (aries-core)
    - TestCafe (aries-site)
  Actions: --> Implement checks with Git Hooks
2. During build (i.e. evaluate which dependencies are bundled, caching, etc.)
  - Move any applicable dependencies to peerDependencies or devDependencies
  - Cache dependencies
  Actions: --> Update package.json s
3. When do builds get triggered
  - Do we run builds on all branches? Or just specific ones?
  Actions: --> Recommend leave alone for now. Deploy previews are useful for PR and stakeholder reviews. Opportunity in the future if needed.
