### ISSUE TITLE
Button Pattern 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#307]
Primary, Default, Secondary, Light/dark

**Comment by gregfuruiye** [comment]
here's a link to button for figma.
https://www.figma.com/file/Y0MvUtkdobqCk0X56fZB6j/hpe-design-system-library-button?node-id=0%3A1

**Comment by ShimiSun** [comment]
https://github.com/grommet/grommet/pull/3739
https://github.com/grommet/grommet-theme-hpe/pull/12
