### ISSUE TITLE
Anchor Pattern 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#308]
Light/dark

Add the [following examples](https://www.figma.com/file/I7PsiUmvr7OEJ6311rBUfg/hpe-design-system-library-anchor?node-id=0%3A1) to Controls page:
- Anchor standalone
- Anchor inline text
- Anchor w/ icon
- Anchor underline

Work to consider:
1. Which executions is the 'default' anchor --> this will need to be adjusted in `grommet-theme-hpe`
2. How do we want to allow for styling by use case? (e.g. default vs. inline vs. underline)
  - What is the interface? Create a `type` prop?
  - Implement in `anchor.extend` in the `grommet-theme-hpe`?
3. Clean up all usage throughout `aries-site`
4. Remove Anchor components from `aries-core`

**Comment by gregfuruiye** [comment]
Adding link to anchor file.

https://www.figma.com/file/I7PsiUmvr7OEJ6311rBUfg/hpe-design-system-library-anchor?node-id=0%3A1
