### ISSUE TITLE
Type Pattern

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#309]
Heading, Paragraph, Text, Labels, Light/dark

**Comment by gregfuruiye** [comment]
https://www.figma.com/file/oJhw3JqMemtbwWjlLPWW5O/hpe-design-system-library-typography?node-id=0%3A1

**Comment by MikeWalrath** [comment]
@ShimiSun  can you take a look at the link above and verify if there is anything that stands out to you that would require any further discussion?

**Comment by ShimiSun** [comment]
I think it is fine, I haven't tested it all but as long as it built correspondingly  https://github.com/grommet/grommet-theme-hpe/blob/master/src/js/index.js and matching its text sizes values.
