### ISSUE TITLE
Color Pattern

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#310]
Light, Dark, Core, Background, Text

**Comment by gregfuruiye** [comment]
https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/hpe-design-system-library-color?node-id=0%3A1

**Comment by halocline** [comment]
Questions:
- Re: implementation
  - Are we simply updating the Color page to reflect each of the sections in the Figma doc?
  - Difference between 'Brand - Secondary' and 'Design System - Core'?
  - Call to Action Text - green specified is not in our palette colors.
  - Status colors - Add to page?
  - Status colors - green hex value looks funny, extra f? correct green?

- Reconciliation of the following discrepancies between [grommet-theme-hpe](https://github.com/grommet/grommet-theme-hpe/blob/master/src/js/index.js) and [Figma Colors](https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/hpe-design-system-library-color?node-id=0%3A1)
  - text.light - #333333 vs. #444444 
  - text.dark - #EEEEEE vs. #DDDDDD 
  - background-back.light - #EFEFEF vs. #EDEDED 
  - background-front.dark - #222938 vs. #272E3F
  - background-contrast.light - #11111108 vs. #CCCCCC30
  - background-contrast.dark - #FFFFFF08 vs. #CCCCCC30
  - red! - #FF0000 vs. #A2423D
  - red.light - #FF4F4F vs. #A2423D
  - red.dark - #4B1916 vs. #64221E
  - control - brand vs. #00C781

**Comment by gregfuruiye** [comment]
Added a Color tile with text guidance on the figma file

**Comment by britt6612** [comment]
Thank you Ill add that in
