### ISSUE TITLE
Implement Testing of Other Navigational Components

### ISSUE THREAD

**Issue by taysea** [hpe-design/design-system#332]
To be included in initial tests (which should be able to test cross browser):
- [x] HomeTiles can be clicked on (or tab + enter key) --> routes to correct page
- [x] NavPage list items can be clicked on (or tab + enter key) --> routes to correct page
- [x] "Topic" above content page header can be clicked on (or tab + enter key) --> routes to topic page
- [x] Sidebar nav link can be clicked on (or tab + enter key) --> routes to correct page
- [x] NextContent can be clicked on (or tab + enter key) --> routes to correct page

**Comment by britt6612** [comment]
I cant edit your original comment! 

Done 
- [x] HomeTiles can be clicked on (or tab + enter key) --> routes to correct page
- [x]  NavPage list items can be clicked on (or tab + enter key) --> routes to correct page
- [x]  "Topic" above content page header can be clicked on (or tab + enter key) --> routes to topic page
- [ ]  Sidebar nav link can be clicked on (or tab + enter key) --> routes to correct page
- [x]  NextContent can be clicked on (or tab + enter key) --> routes to correct page

Still need to work on SideBar nav with tab and enter key
