### ISSUE TITLE
HPE Theme 2 Component Sticker Sheet

### ISSUE THREAD

**Issue by L0ZZI** [hpe-design/design-system#350]
Coverage of the grommet base components with the updated HPE theme.

**Comment by L0ZZI** [comment]
Made a dent...Menu, Form Imputes, Icons, Tabs, Accordion, amongst the base stuff. 
https://www.figma.com/file/K0PppsSh6aQSszqlwKAekg/hpe-design-system-stickers?node-id=0%3A1

**Comment by L0ZZI** [comment]
Next steps are table, viz stuff like charts, meters, bars, and image/video content....

**Comment by ericsoderberghp** [comment]
Chris and I had a long review of this this afternoon and came up with an assortment of updates to the sticker sheet as well as some pending updates needed in grommet to support some aspects. The grommet changes needed include:

- [ ] CheckBox and RadioButtonGroup enhancements to support border and focus around the whole component, to align it more with TextInput in a Form context. I am thinking this would include adding a new property or property value but not impacting compatibility of the current behavior.
- [ ] TextInput and MaskedInput enhancements for a `decorator` property that could be used for a search icon or units indication within the input element.
- [ ] RadioButtonGroup enhancement to remove the visible button input and instead have all of the content function like a button.
- [ ] Text enhancement to add one or more larger sizes for use as big numbers, at least `xxxlarge` but maybe more. I am also thinking of adjusting the font scaling algorithm in the grommet-theme-designer to be a bit simpler and would include this there as well.

**Comment by ericsoderberghp** [comment]
Some other notes on Card, Grid, List, and ListItem that I thought I'd preserve here:

- a Grid contains Cards and has a gap when it does
- a Card can contain an Identifier, above or below
- a Card has a column layout
- a Card can show interaction: hover, active, etc.
- a Card has chrome, border, background, elevation, etc.
- a List does not contain Cards
- a List contains ListItems and doesn’t have a gap
- a ListItem can contain an Identifier
- a ListItem has a row layout
- a ListItem can show interaction: hover, active, etc.

**Comment by ericsoderberghp** [comment]
And lastly, some notes on Identifier:
- an Identifier can contain a label, an icon, or both
- an Identifier can contain a subLabel, but only if it has a label
- an Identifier has t-shirt sizing, at least 'small', 'medium', and 'large'
