### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by gregfuruiye** [hpe-design/design-system#354]
Did footer to just keep moving forward on some easy work and keep content rolling. Matched what is currently being used by brand and brand guidelines. Removed logo and added additional copyright text.

https://www.figma.com/file/9aoCaf5lqzdQv1q4NFi0GN/hpe-design-system-library-footer?node-id=0%3A1

**Comment by halocline** [comment]
Mobile execution?

**Comment by halocline** [comment]
@gregfuruiye Now that the mobile spec is added, do you feel this is ready for dev?

**Comment by halocline** [comment]
@britt6612 This is a good one for you to pick up once Greg confirms it is ready for dev.

**Comment by gregfuruiye** [comment]
I made some color corrections and added mobile dark mode. We should be all good now.

**Comment by britt6612** [comment]
@gregfuruiye thank you 😊
