### ISSUE TITLE
No background fill on light theme examples.

### ISSUE THREAD

**Issue by L0ZZI** [hpe-design/design-system#355]
When switching from dark to light theme, the background box isn't using the background-front prop? is this part of #180 ?

![Screen Shot 2020-02-11 at 6 57 37 AM](https://user-images.githubusercontent.com/1753301/74248170-06263d80-4c9c-11ea-83ea-b39e1b41a5bb.png)
![Screen Shot 2020-02-11 at 6 57 33 AM](https://user-images.githubusercontent.com/1753301/74248172-06bed400-4c9c-11ea-83f1-61158758ef81.png)

**Comment by halocline** [comment]
@L0ZZI Yes, https://github.com/hpe-design/design-system/issues/180 will fix this. `background-back` `#EFEFEF` will be applied and `background-front` will remain `#FFFFFF`.
