### ISSUE TITLE
Templates - Add Templates Tile & Supporting Content

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#374]
### Is this issue related to the design system core library or design system website?  
Design System Website 

### Expected Behavior

https://www.figma.com/file/jWRCRfkiQSO6E9TlKAerml/design-system-tweak?node-id=0%3A1

- [x] Should have Templates tile on home page (icon, heading, description, color)
- [x] Should have Templates `NavPage` containing list of content pages (e.g. Sign In Template, Dashboard/Tile Template, Service List Template)
- [ ] Each content page needs an icon and description
- [x] Template content pages

**Comment by MikeWalrath** [comment]
@taysea is this blocked because of the icons and description?

**Comment by taysea** [comment]
@MikeWalrath Yes, we'll need copy for these pages. Going to share a deployment sometime mid-morning today and that should help demonstrate what kind of text/icons we might need if the proposed structure is accepted.
