### ISSUE TITLE
Form Patterns - Scope

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#375]
Pattern Scope:
- [x] Form templates (these are examples which present a form layout tailored to a specific use case -- examples should showcase the form presentation in context of the use case)
  - [x] Sign In
  - [x] Account Creation Flow 
  - [x] Checkout 
  - [x] In-App Configuration (e.g. Manage User in slideout)
- [x] Form interaction patterns (these are examples which showcase interactivity, help messaging, required / error states, suggestions, focus, etc. independent of specific use-case)
  - [x] Anatomy
  - [x] States
  - [x] Spacing (?)
  - [x] Interactions
  - [x] Visual Spec (?)

**Comment by L0ZZI** [comment]
I thinkI got most of this done from a design perspective today, https://www.figma.com/file/K0PppsSh6aQSszqlwKAekg/hpe-design-system-stickers?node-id=0%3A1

Want to review with @halocline, @gregfuruiye and @ericsoderberghp to do some clean up and tightening.
