### ISSUE TITLE
Login Pattern 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#377]
### URL, screen shot, or CodeSandbox exhibiting the issue

https://hpe.invisionapp.com/share/KGU7BMHUCXV#/screens/386832391

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Design System version:
- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by gregfuruiye** [comment]
Adding link to Figma File:

https://www.figma.com/file/ldCn2p3XV2Lc5WYafzyFyj/hpe-design-system-library-login?node-id=0%3A1
