### ISSUE TITLE
Explain how to begin using HPE theme

### ISSUE THREAD

**Issue by halocline** [hpe-design/design-system#463]
Relevant question on Grommet Slack:

https://grommet.slack.com/archives/C04LMHN59/p1583353150158200

- Design Site should bring awareness and introduction to the theme, plus reference the Github repo
- Details of how to implement should be left to the repo Readme.

**Comment by ericsoderberghp** [comment]
I am thinking this should be within the Develop page. In: https://github.com/hpe-design/design-system/issues/438
