### ISSUE TITLE
Resolve button discussion regarding button styling of hover, pad, border, etc.

### ISSUE THREAD

**Issue by taysea** [hpe-design/design-system#466]
Based on some designs and other previous discussion around button, there has been a discussion about adding additional control to how users can style buttons. The discussion that needs to be resolved is:
a) What are the levels of control we want to add for the user (some topics were pad, border, background, and active/hover states)
b) Where do these controls live? In the theme or as props? (It may differ for different styling aspects)

What initially prompted this discussion is that currently "icon only" buttons vs "icon + label" buttons have different padding and because of that, achieving the sidebar designs would not be possible (by just using button -- there could be work arounds by using box and button as wrapper, etc.):
<img width="874" alt="Screen Shot 2020-03-05 at 3 13 19 PM" src="https://user-images.githubusercontent.com/12522275/76034472-e2999000-5ef3-11ea-9af7-8e82e19e348d.png">

**Comment by ericsoderberghp** [comment]
After several face to face discussions over the last few work days, here are some thoughts.

Add a property to `Button` that means "maintain consistent height of the Button whether it has an icon or label or both".
This is orthogonal to whether it is `primary`, so that it can be used in toolbars.

At first, I was thinking about what to name the property: `tall`, `fat`, `phat`, `iconic`.

But then, I was thinking we could do something more along the lines with how we were talking about using it. How about calling it `collapse`, when `true` we will reduce it to just an icon, when `false` we will preserve the height that we would have if there was an icon?

**Comment by L0ZZI** [comment]
I think it's `props` and your characteristics I think are right; border, background, and elevation based on active/hover states are correct. 

For how we have a conceptual model to express the style usage/state would for me be more like, `visual`(background fill/opacity change), `simple` (stroke paint), `chrome` (elevation/effect), `plain`(follow button). 

Making any sense?

**Comment by ShimiSun** [comment]
Sharing an idea I had in mind. 
Add a prop that accepts a string of the context the Button is in. 
In our use case, we are trying to solve the Button layout for the context of a 'sidebar', and maybe a future context of it could be a footer or a form, etc. This is why I think we should keep this prop modular ("string") rather than true/false values. 

Something like:
```
<Button icon={<Icon />} label="Button" context="sidbar" />
```
other names for `context` could be `visualParent`, `group`, `parent` or something that express the intention of it.

**Comment by ericsoderberghp** [comment]
How would Button use that? Would just the presence of the property cause the height alignment behavior?

Also, I think `context` is a well defined term in React already. I think we would need another term.

**Comment by taysea** [comment]
React Bootstrap and MaterialUI use the prop `variant` to accept a string that applies different stylings. For example, variant could accept `primary`, `outlined`, `contained`, etc.

**Comment by taysea** [comment]
What about `uniform`? If true, then padding for an icon only or icon + label button would be the same, if undefined then behavior is how button currently works.

Or, `variant='uniform'`?

Other word ideas that could be used in the same way: `simple`, `flat`, `collapsible` (circling back to your suggestion now haha)?

@ericsoderberghp

**Comment by ericsoderberghp** [comment]
It was interesting to encounter a similar need for CheckBox, RadioButtonGroup, and RangeInput in the context of aligning in a Form context. These all fit the pattern of "aligning with other things".

**Comment by taysea** [comment]
I do agree that those are about aligning with other things. It feels like this button styling is more about aligning it with itself as opposed to with other things. But maybe I'm just thinking about it a little different.

And so going down the path you're talking about, we might have a prop called `aligned` that when true it would apply the padding on this button or modify those other components in a way that aligns them correctly in a Form context and when undefined would just behave as it is already? Typing through this now I feel like this might make sense.

**Comment by ericsoderberghp** [comment]
That's the direction I'm thinking. Except, `align` already has some meaning elsewhere in grommet that feels just different enough from this situation to make me want a different term. `proportionate`, `regular`, `normalized`, `leveled`, `consistent`, `uniform`?

**Comment by ShimiSun** [comment]
I like the combination of `normalized` and `leveled` together, I think it drives the point home better when combined together. `normalized` by itself can be any type of normalization (color, layout,  padding...) and `leveled` is implying the padding, `normalizeLevel` may sound awkward though it tells the story a little better IMO.

**Comment by taysea** [comment]
I kind of like `normalizedLevel` or `uniform`

**Comment by ericsoderberghp** [comment]
I am gravitating towards `normalized`. `level` seems related to `<Heading level />`. Normalized also gives us some flexibility of meaning. Eventually, if we want to have shades of normalization, we can have that prop take an object. But, for now, we can have it just be a boolean that means, style it in a way that will make it fit in with its peers. So:

`<Button normalized />` means consistent padding with other normalized Buttons, regardless of icon or label combinations.
`<CheckBox normalized />` means consistent border and padding with other input controls, like TextInput. This would work for `RadioButtonGroup` and the eventual `CheckBoxGroup` as well.

**Comment by taysea** [comment]
I am comfortable with this approach and the flexibility it lends us in the future.
