### ISSUE TITLE
Incorporate User Feedback - Create proposed order of tiles

### ISSUE THREAD

**Issue by halocline** [hpe-design/design-system#481]
Sub issue to: https://github.com/hpe-design/design-system/issues/474

"home page tiles for just templates, components, and foundation. Remove Resources tile. Change Develop and Design to be more subtle, not tiles."

**Comment by britt6612** [comment]
Discussed with @gregfuruiye and both agreed that instead of just reordering tiles there would be some design changes to how some of the tiles will be subtle and not full tiles.
