### ISSUE TITLE
Serve HPE fonts from CloudFront

### ISSUE THREAD

**Issue by ericsoderberghp** [hpe-design/design-system#506]
Email that triggered this:

On Mar 10, 2020, at 1:30 PM, Vilrokx, Mark <mark.vilrokx@hpe.com> wrote:

Hi Eric & Chris,
 
I am looking for the owner of the HPE Fonts that are hosted on AWS S3, more specifically:
https://hpefonts.s3.amazonaws.com/web/MetricHPE-Web-Regular.woff
https://hpefonts.s3.amazonaws.com/web/MetricHPE-Web-Bold.woff
https://hpefonts.s3.amazonaws.com/web/MetricHPE-Web-Semibold.woff
https://hpefonts.s3.amazonaws.com/web/MetricHPE-Web-Light.woff
 
I was given your names by a colleague so I am hoping you can help me, or point me in the right direction.
 
I am trying to find out if these .woff files can be hosted on a server that supports http/2 instead of http/1.1, as they are now. Given that they are on S3 already, this should be a simple change (I can help!).
 
Please let me know if I am knocking on the right door of I you know where I should go to instead.
 
Cheers,
Mark.

Follow up:

Hi Eric,
 
Awesome, thanks.
 
S3 does not support http/2 as far as I am aware, however, you can simply serve your S3 assets from AWS CloudFront, which does support http/2. This has the added advantage that your assets will be delivered faster as they will be served up from a location closer to your clients.
 
Once enabled, please let us know what the CloudFront URL to your font assets is and we will update our css to point to the CloudFront served .woff files.
 
(You original S3 URLs will keep working, but you should consider changing that)
 
Cheers,
Mark.

**Comment by halocline** [comment]
Related issue: https://github.com/hpe-design/design-system/issues/644

**Comment by halocline** [comment]
@ericsoderberghp , @karatechops , @ShimiSun -- Do any of you have the AWS credentials needed to get a CloudFront instance up and running?

**Comment by ericsoderberghp** [comment]
I don't think I have any. Alex?

**Comment by karatechops** [comment]
I can spin one up but would prefer not to manage it. I've reached out to the team who manages HPE's AWS account (hpe-aws-ma@hpe.com) to get you set up.

**Comment by halocline** [comment]
Current Status:
- S3 bucket setup and hosting MetricHPEXS fonts in .woff, .woff2, and .otf
- CloudFront distribution in placing and serving fonts. Examples:
  - https://d3hq6blov2iije.cloudfront.net/fonts/HPEXS-Metric-Fonts/MetricHPEXS-Regular.woff2
  - https://d3hq6blov2iije.cloudfront.net/fonts/HPEXS-Metric-Fonts/MetricHPEXS-Regular.woff
  - https://d3hq6blov2iije.cloudfront.net/fonts/HPEXS-Metric-Fonts/MetricHPEXS-Regular.otf
- PR to add to `grommet-theme-hpe` NEXT here: https://github.com/grommet/grommet-theme-hpe/pull/73

**Comment by ericsoderberghp** [comment]
> @ericsoderberghp Would you like me to message [mark.vilrokx@hpe.com](mailto:mark.vilrokx@hpe.com) with the updated URLs?

Good reminder. I just replied, and CC'd you.

**Comment by mvilrokx** [comment]
👍

**Comment by mvilrokx** [comment]
@ericsoderberghp Can you confirm that these are the same fonts as MetricHPE-Web-Light/Regular/Bold.woff since the names have changed.

**Comment by L0ZZI** [comment]
@mvilrokx, the characters are all the same. The reason for the change was to adjust the default baseline and tighten the line-height to make better out of the box alignment of the the typeface as a whole.  Example attached. 

![metrichpexs-comparo](https://user-images.githubusercontent.com/1753301/83785104-ac2ff600-a645-11ea-8614-870739cbc5e8.png)

**Comment by mvilrokx** [comment]
ok, I'm not a font expert :-), but judging by the Red box around the font, it seems that this should _not_ re-arrange layouts if we use the new version of the font?

**Comment by L0ZZI** [comment]
I don't think. 😁 The character spacing and everything else is the same. If you're using the HPE theme, most of the line-heights are calculated in the components, so any shifting should be subtle.
