### ISSUE TITLE
Accordion 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#512]
# Accordion 
An accordion is a list of headers that hide or reveal additional content when selected.

Acceptance criteria is based on alignment across the below 
- [x] Figma 
- [ ] Theme
- [ ] Grommet
- [ ] Code Examples
- [ ] Guidance  

## Figma link
https://www.figma.com/file/UvTBUQdhk07wV79nijsrtr/HPE-Accordion-Component?node-id=71%3A25

## Design Proposal
![Screen Shot 2020-03-13 at 12 48 29 PM](https://user-images.githubusercontent.com/1753301/76654747-f57e1700-6528-11ea-925d-c01f9e43fd15.png)

**Sticker Sheet Reference**
https://www.figma.com/file/K0PppsSh6aQSszqlwKAekg/hpe-design-system-stickers?node-id=424%

## Fit Criteria
- Align Accordion to Button Component's pads, text size, and spacing
- Each accordion item should be a separate component (it should be a modular component allowing for a designer to craft a variety of accordion items
- Provide enabled, disabled, hover, active, and focus states
- Ensure your Figma frames/art-boards and the artwork within are built to be responsive
- Follow thumbnail and file formatting standard when submitting to the Design System Lib

## Open Items
- Placement of the expand collapse arrow on left or right side of row?
- Can the user change the icon via nested component? 
- Does the Accordion component have min/max width?

**Comment by ericsoderberghp** [comment]
Some guidance starters:
- when to use Accordion vs. Layer vs. navigation to another page?
- keep the labels simple
- avoid lengthy panel content
