### ISSUE TITLE
CheckBox 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#514]
# CheckBox
A checkable input that communicates if an option is true, false or indeterminate

Acceptance criteria is based on alignment across the below 
- [x] Figma 
- [ ] Theme
- [x] Grommet
- [x] Code Examples
- [x] Guidance  

## Design Proposal

**Figma File**
https://www.figma.com/file/7Mm1xDBTOtPHqggEVpaD2N/hpe-CheckBox-Toggle?node-id=1433%3A591

![Screen Shot 2020-03-13 at 2 08 15 PM](https://user-images.githubusercontent.com/1753301/76659613-21eb6080-6534-11ea-84ca-1d3b7370b0c6.png)

**Sticker Sheet Reference**
https://www.figma.com/file/K0PppsSh6aQSszqlwKAekg/hpe-design-system-stickers?node-id=425%3A0

## Fit Criteria
- Grommet and by proxy the HPE Design System is redefining what "Plain" means from a property of elements in the theme. Ensure checkBox supports both the plain and styled treatments for all states
- In example, reference a default design that doesn't have the checkbox icon
- Provide enabled, disabled, hover, active, and focus states (plus states for when the element has already been checked)
- Ensure your Figma frames/art-boards and the artwork within are built to be responsive
- Follow thumbnail and file formatting standard when submitting to the Design System Lib

## Open Items
- Need an example of checkBox indeterminate, this is something that comes into play more in checkBoxGroup, but should be part of this execution.
- Explore displaying secondary information in checkBox row

**Comment by vavalos5** [comment]
https://www.figma.com/file/G6hvLNbHo9wCxZTMGGOyKq/hpe-design-system-library-checkbox?node-id=0%3A1

**Comment by ericsoderberghp** [comment]
Some guidance starters:
- keep the label short but descriptive enough
- when to use CheckBox vs. CheckBoxGroup
- when to use a single CheckBox vs. a RadioButtonGroup with two buttons, or Select with two options?
- default to the most frequently chosen option.

**Comment by britt6612** [comment]
Thoughts after discussion: 

Looking at `checkbox` outside of a `formfield` 
In designs there is a border around `checkbox` it should be noted that `checkbox` alone with not have a border out of the box with `grommet` This should be addressed and how `checkbox` will be used
