### ISSUE TITLE
Layer 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#515]
# Layer
Acceptance criteria is based on alignment across the below 
- [x] Figma 
- [x] Theme
- [x] Grommet
- [ ] Code Examples
- [x] Guidance  

## Design Proposal
![Screenshot]()

**Figma File**
https://www.figma.com/file/Ts53TAipMolmsv9DxWG3p0/HPE-Layer-Component?node-id=2%3A22
## Fit Criteria
- 
## Open Items
-

**Comment by ericsoderberghp** [comment]
Some guidance starters:
- when to use Layer vs. progressive disclosure within the page vs. navigation to another page
- positioning of Layer, Forms on right, notifications above or below
- when to use modal?
- where to put a close control? Is it always visible if the content scrolls?

**Comment by gregfuruiye** [comment]
Moved Figma file into the library and updated the Figma link.
https://www.figma.com/file/Ts53TAipMolmsv9DxWG3p0/HPE-Layer-Component?node-id=2%3A22

**Comment by gregfuruiye** [comment]
Here's a first pass at the guidance for layer.

**Guidance**
Layer is used to define the properties and behaviors of an overlay for things like a modal dialog or notification. The content of the Layer is defined by the [Box component](https://design-system.hpe.design/components/box).

**Create**
- Define the container, content, location, and any animation, depending on the intent of the use case (like a notification or modal with a form).
- Use the [Box component](https://design-system.hpe.design/components/box) to define the content of your layer.
- Ensure that any next steps for the user are provided to progress or close out of the layer.

**Best Practices**
- Modal is best applied when you need to center attention on specific content, a task, or behavior and not allow interactivity with the underlying content.
- Target positioning should be 
- Position forms to the right (sidedrawer).
- Position notifications top or bottom.
- Use a close control to guide users to move out of the layer. Provide an alternative to move out of the layer by allowing use of the 'esc' key or clicking off the container of the layer.
- Layer is not great for navigation as it 'hides' content. Maintain context for the user with layer.

**Accessibility**
- Consider the use of ARIA role=dialog to implement a modal for screen readers.

**Comment by ShimiSun** [comment]
@greg, thanks, I'm on it!
