### ISSUE TITLE
MaskedInput 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#516]
# MaskedInput
A form of TextInput, the input can be constrained by a string expression defined by a developer

Acceptance criteria is based on alignment across the below 
- [ ] Figma 
- [ ] Theme
- [x] Grommet
- [x] Code Examples
- [x] Guidance  

## Design Proposal
![Screen Shot 2020-03-13 at 2 43 43 PM](https://user-images.githubusercontent.com/1753301/76661594-0df62d80-6539-11ea-8096-cc708f3782c4.png)

**Sticker Sheet Reference**
https://www.figma.com/file/K0PppsSh6aQSszqlwKAekg/hpe-design-system-stickers?node-id=422%3A102

**Figma File**
https://www.figma.com/file/fO285pXUqN9pVZ0xpRoKjL/HPE-Masked-Input-Component?node-id=0%3A1

## Fit Criteria
- Recommend completing the TextInput designs first as much of this is supplemental to that component set 
- The sticker sheet reference shows a couple use cases. Minimum reuqieremnt is, phone, date, data/time, date range, and size w/units—Reference [grommet storybook](https://storybook.grommet.io/?path=/story/maskedinput--date) to see more references
- Provide enabled, disabled, hover, active, and focus states (plus states for when the element has already been checked)
- Ensure your Figma frames/art-boards and the artwork within are built to be responsive
- Follow thumbnail and file formatting standard when submitting to the Design System Lib

## Open Items
- We'll need to work with product teams to define some more of the interesting edge cases for MaskedInput as there is IP, IP Ranges, Consumption and Data types that might have a bunch of mutations, we'll need to explore what other areas need examples initially
-  Validation will be contingent on the developers definition, we'll need to see how much guidance we'll need on info, label, validation, and error messaging

**Comment by ericsoderberghp** [comment]
Some guidance starters:
- restrict the syntax as much as possible, but no more
- provide suggestions or options wherever possible
- ensure the control works via typing alone, automatically inserting separators if needed but allowing them if typed
- use this whenever there is a formalized syntax, in preference to multiple Select inputs, or a TextInput with descriptive syntax help and validation
