### ISSUE TITLE
RadioButtonGroup 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#518]
[PR](https://github.com/hpe-design/design-system/pull/735)
[Preview](https://deploy-preview-735--keen-mayer-a86c8b.netlify.app/components/radiobuttongroup)

# RadioButtonGroup
A select list that can have a single entry checked at any one time

Acceptance criteria is based on alignment across the below 
- [x] Figma 
- [x] Theme
  - [x] Identify which styling items require Grommet enhancements
  - [x] Create issues to represent Grommet work https://github.com/hpe-design/design-system/issues/898
  - [x] Add to grommet-theme-hpe https://github.com/hpe-design/design-system/issues/843
- [x] Grommet https://github.com/hpe-design/design-system/issues/898
- [x] Code Examples
- [x] Guidance  

## Design Proposal
![Screen Shot 2020-03-13 at 2 22 21 PM](https://user-images.githubusercontent.com/1753301/76660431-257fe700-6536-11ea-8e95-985f15a2f5c4.png)

**Figma File**
https://www.figma.com/file/aZyY606ENQedz4FXugdzgS/HPE-Radio-Button-Group-Component?node-id=105%3A643

## Fit Criteria
- Grommet and by proxy the HPE Design System is redefining what "Plain" means from a property of elements in the theme. Ensure radioButtonGroup supports both the plain and styled treatments for all states
- In example, reference a default design that doesn't have the radioButton icon
- Provide enabled, disabled, hover, active, and focus states (plus states for when the element has already been selected)
- Ensure your Figma frames/art-boards and the artwork within are built to be responsive
- Follow thumbnail and file formatting standard when submitting to the Design System Lib

## Open Items
- Explore displaying secondary information in checkBox row
- Reference other examples of checkbox on [hpe design sys site](https://design-system.hpe.design/components/input#radiobuttongroup) and on the [figma sticker sheet](https://www.figma.com/file/K0PppsSh6aQSszqlwKAekg/hpe-design-system-stickers?node-id=259%3A87)

**Comment by ericsoderberghp** [comment]
Some guidance starters:
- keep the labels simple wherever possible. Avoid long text descriptions as the label.
- when the number of options gets longer than about 5, or if the default value is reasonable most of the time, consider using Select instead, to avoid cluttering the experience.

**Comment by halocline** [comment]
To Dos:
- Grommet is missing `radioButton.color` in `base.js` and in documentation, but is included in implementation here: https://github.com/grommet/grommet/blob/6219ed0086c8673692ff78ca6a31d710f550ed79/src/js/components/RadioButton/RadioButton.js#L29

**Comment by halocline** [comment]
Created issues for all outstanding work: https://github.com/hpe-design/design-system/issues/898
