### ISSUE TITLE
Select 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#520]
Acceptance criteria is based on alignment across the below 
- [x] Figma 
- [x] Theme
- [x] Grommet
- [x] Code Examples
- [x] Guidance  

Figma file:
https://www.figma.com/file/fZJdRcNrvZ1JjdPRYHpFFU/hpe-design-system-library-select?node-id=0%3A1

**Comment by halocline** [comment]
Related: https://github.com/hpe-design/design-system/issues/657

**Comment by halocline** [comment]
Hey @vavalos5 ! Letting you know that I am going to start modifying the [Select page](https://design-system.hpe.design/components/select). I'll send you a link once the basics are in place, then, perhaps we can review and talk through any adjustments / remaining work needed to be done?

**Comment by vavalos5** [comment]
Making note here that I've still got to make changes to select by adding a a grid. Shouldn't interfere w/ devs.

**Comment by halocline** [comment]
Dev items to address:
- [ ] Changing icon from `FormDown` to `FormUp` when drop is open will require updates to Grommet:
  - [ ] Modify which [icon is passed to](https://github.com/grommet/grommet/blob/cebbd7591bf5fb4c0ecc52f84a33cb1c0cd7da40/src/js/components/Select/Select.js#L158) `SelectIcon` in `Select.js` -- dependent on [open state](https://github.com/grommet/grommet/blob/cebbd7591bf5fb4c0ecc52f84a33cb1c0cd7da40/src/js/components/Select/Select.js#L128)
  - [ ] Add `theme.select.icons.up` to `base.js`
  - [ ] Allow icon prop to accept object?

**Comment by ericsoderberghp** [comment]
Just a note that I don't think we should be requiring callers to set the icon based on up/down state via a property. That should be controllable via the theme.

**Comment by halocline** [comment]
Status update:
- Site PR is up - [PR](https://github.com/hpe-design/design-system/pull/665) - [Preview](https://deploy-preview-665--keen-mayer-a86c8b.netlify.app/components/select) -
- Theme PR is in need of review/merge to NEXT - https://github.com/grommet/grommet-theme-hpe/pull/46
- Grommet PR in the works to allow styling of FormField based on disabled state

**Comment by MikeWalrath** [comment]
@halocline @vavalos5 We are very close here but noticing some discrepancies on the below.
1) Active color 
2) Selected text color 
3) Vertical padding

**Comment by vavalos5** [comment]
@MikeWalrath Where are you seeing the second screen shot you posted?

**Comment by ericsoderberghp** [comment]
https://designer.grommet.io/select?id=HPE-design-system-hpedesignsystem-hpe-com

**Comment by vavalos5** [comment]
Thanks Eric. There were color changes recently. My file is up to date.

**Comment by ericsoderberghp** [comment]
I think figma is OK, it's the theme side that needs alignment.

**Comment by halocline** [comment]
Theme PR filed: https://github.com/grommet/grommet-theme-hpe/pull/53

Note the selected text and background colors have changed since review on Friday -- PR reflects current state.
