### ISSUE TITLE
Tabs 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#522]
# Tabs
Acceptance criteria is based on alignment across the below 
- [x] Figma 
- [x] Theme
- [x] Grommet
- [x] Code Examples
- [x] Guidance  

## Design Proposal
![Screenshot]()

**Sticker Sheet Reference**
![Figma link]()

**Figma Link** 
https://www.figma.com/file/Kp4dWyhUTnKIJ1Cg5CoL9o/hpe-design-system-library-tabs?node-id=0%3A1

## Fit Criteria
- 
## Open Items
-

**Comment by taysea** [comment]
After reviewing the Tabs designs with Maggie, here are some take-aways about changes on the dev side:
- Adding an icon to a Tab requires us to create a more complex `title` such as the one seen here: https://storybook.grommet.io/?path=/story/tabs--rich -- I'm wondering if it's a common use case for users to add icons to tabs if we'd want to add an `icon` prop and `reverse` prop to Tab like there is for Button.

The rest can be achieved via the theme.

Waiting on colors to be finalized before updating NEXT branch of the theme.

**Comment by ericsoderberghp** [comment]
I'm open to adding `icon` and `reverse` to Tab, which I'm hoping will just be passed through to an underlying default Button.

**Comment by ericsoderberghp** [comment]
Some guidance starters:
- keep the number of tabs short, at most 5
- keep the labels short
- when to use Tabs vs. Layers vs. navigating to a more detailed screen/page?
- avoid combining Tabs as a navigation structure along with global sidebar and app nav header, too much navigation chrome (we should discuss this concept under navigation too)
- if Tabs are a primary navigation structure, connect them to the browser location

**Comment by taysea** [comment]
In terms of `Variants` do we want to show one visual/code variant as "Tabs as navigation"? or just provide written guidance on how to use it correctly as navigation if someone were to want to
