### ISSUE TITLE
TextArea 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#523]
Acceptance criteria is based on alignment across the below 
- [x] Figma 
- [x] Theme
- [x] Grommet
- [x] Code Examples
- [x] Guidance  

Figma file:
https://www.figma.com/file/evH1LQewFPc8Y2fteywMxM/hpe-design-system-library-text-area?node-id=0%3A1

**Comment by taysea** [comment]
All styling can be resolved in the theme, but one potential issue with TextArea is how it resizes when inside a formfield -- the user is able to drag the text area wider than the space allotted by the formfield.

**Comment by ericsoderberghp** [comment]
https://v2.grommet.io/textarea?#resize

**Comment by taysea** [comment]
Nice, so I assume in the context of a formfield, we'd want to encourage use of resize=false?

**Comment by ericsoderberghp** [comment]
Probably `resize="vertical"`

**Comment by ericsoderberghp** [comment]
Some aspects for guidance:

- use TextArea for multi-line text input, such as notes or comments
- set the number of rows to approximate the typical number of rows expected
- allow the user to resize vertically within a form field context and resize both directions otherwise
