### ISSUE TITLE
TextInput 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#524]
# Text Input Field
Acceptance criteria is based on alignment across the below 
- [x] Figma 
- [ ] Theme
- [x] Grommet
- [x] Code Examples
- [x] Guidance  

## Design Proposal
**Figma File**
https://www.figma.com/file/E40Oo2MpdRNMyVaJqfJ0Wd/hpe-design-system-library-text-input?node-id=1%3A38

**Sticker Sheet Reference**
https://www.figma.com/file/K0PppsSh6aQSszqlwKAekg/hpe-design-system-stickers?node-id=1%3A2

**Comment by vavalos5** [comment]
Started Figma file + added Figma file to issue description

**Comment by taysea** [comment]
A couple quick comments from what was discovered last week:
- Theme has been updated to have the correct padding
- Browser <input> doesn't support line-height, so the dimensions are off because we are losing the line-height from the font. We will need to look int how to adding this back in.

**Comment by ericsoderberghp** [comment]
Is it that the browser's don't support line-height or that grommet doesn't pull it from the theme?

**Comment by taysea** [comment]
Per investigation, we can add it to the theme. The plan is to add the following to `global.input`:
```
input: {
   font: {
      size: {},
      height: {},
      weight: {},
   },
},
```
If `input.font.weight` is undefined it will fallback to `input.weight` which already exists.

**Comment by ericsoderberghp** [comment]
Some things for guidance:

- use TextInput to collect arbitrary text from the user, such as a name or search input.
- use an icon to reinforce the context
- use MaskedInput if there should be some syntax restrictions, such as an email address, a date, etc.
- provide suggestions liberally, such as prior values for the same field

**Comment by ericsoderberghp** [comment]
Remaining theme work:

> The only things I am seeing are 1) Figma shows formFields having a ‘border-strong’ upon focus, and 2) Figma shows formFields having ‘border-strong’ on error state — currently Designer and Site leave border color as ‘border’ in both of those states.

**Comment by taysea** [comment]
^ Theme work dependent on Grommet PR: https://github.com/grommet/grommet/pull/4028
