### ISSUE TITLE
Search 

### ISSUE THREAD

**Issue by vavalos5** [hpe-design/design-system#584]
Acceptance criteria is based on alignment across the below. Add as a variation within TextInput 
- [x] Figma 
- [x] Theme
- [x] Grommet
- [x] Code Examples
- [x] Guidance  

https://www.figma.com/file/KKHWJN4GAI0Mq5yh0snDT6/hpe-design-system-library-search?node-id=1%3A74

 light mode and dark mode

**Comment by ericsoderberghp** [comment]
some ideas for guidance:
- Search is a refinement of a TextInput, with a Search icon to communicate purpose
- provide suggestions wherever possible
- when the results are visible and quick to filter, results should be filtered live as the user types

**Comment by MikeWalrath** [comment]
Linked to #524
