### ISSUE TITLE
Add images to ContentCards

### ISSUE THREAD

**Issue by halocline** [hpe-design/design-system#589]
ContentCards have "preview Images" of the component/content.

- Create preview image files
- Add file path to `structure.js` `previewImage` properties
 
* Need to add Accordion image since that is the only component not using the actual component example in issue #639 
- [x] Light
- [ ] Dark

Dependent on: https://github.com/hpe-design/design-system/issues/587

## Files needed:

**Templates**
Dashboards:
- [x] Light
- [ ] Dark

Lists:
- [x] Light
- [ ] Dark

Cards:
- [x] Light
- [ ] Dark

Forms:
- [x] Light
- [ ] Dark

**Foundation**
Principles:
- [x] Light
- [ ] Dark

Philosophy:
- [x] Light
- [ ] Dark

Our Brand:
- [x] Light
- [ ] Dark

Color:
- [x] Light
- [ ] Dark

Typography:
- [x] Light
- [ ] Dark

Human Centered:
- [ ] Light
- [ ] Dark

Icons:
- [ ] Light
- [ ] Dark

Content:
- [ ] Light
- [ ] Dark

**Extend**
Global Sidebar:
- [ ] Light
- [ ] Dark

Designer:
- [ ] Light
- [ ] Dark

API Chomp:
- [ ] Light
- [ ] Dark

Table Topper:
- [ ] Light
- [ ] Dark

HPE Docs:
- [ ] Light
- [ ] Dark

HPE Audience:
- [ ] Light
- [ ] Dark

HPE Images:
- [ ] Light
- [ ] Dark

**Comment by britt6612** [comment]
Linking solution @ShimiSun discovered 

https://github.com/hpe-design/design-system/pull/686
