### ISSUE TITLE
Form 

### ISSUE THREAD

**Issue by ericsoderberghp** [hpe-design/design-system#593]
Acceptance criteria is based on alignment across the below 
- [x] Figma 
- [x] Theme
- [x] Grommet
- [ ] Code Examples
- [ ] Guidance  

We need to add some textual guidance explaining some of our recommendations for forms. For example:

- as few fields as possible
- default as much as possible
- progressive disclosure of fields
- how to handle required/optional fields
- variations if providing help guidance text
- the placement of the submit and cancel buttons
- language of buttons, "Add" vs. "Add User"
- how to show errors that aren't tied to a particular field
- how to handle results? ideally result is quick enough to show result immediately in outer context, what about things that take a long time? notifications? always leave the user in control of the UI, don't lock the user to wait for something to complete.

We should at least provide this sort of guidance in the design system site as there will be teams without designers who will not know how to navigate Figma.

**Figma File**
https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=0%3A1

**Comment by ericsoderberghp** [comment]
We should add guidance and an example illustrating "progressive disclosure" for things like "Advanced Options".

**Comment by halocline** [comment]
Sharing some thoughts as I review:

This would be for future scope of work, but I feel like we may want to approach the Form content a bit differently than the “Component page flow.” The detail and guidance on forms is so important I am thinking that this page evolves to where the “Forms” page is a hub, then each of the use cases (e.g. Sign In Form) becomes a standalone page complete with it’s own guidance.

My proposal content flow:
HUB
- **Forms** (this page speaks about form purpose, anatomy, states, accessibility)
  - **Purpose/intro statement**: "Forms provide a way to collect important data from a user. However, this data is only collected effectively when Forms are built in a way that users are inclined to fill out in full."
  - **Guidelines**
    - **General Guidelines**
      - Use as few fields as possible
      - Wrap all input elements in a FormField
      - Fill in default values for as many fields as possible
      - Reveal fields progressively so the user is not overwhelmed
      - Use clear, concise labels for each field
    - **Specific Guidelines** - instructions w/ accompanying examples for each
      - Required vs. optional
      - Progressive/dynamic Feedback to user (e.g. help text, real-time validation, etc.)
      - Button placement and labeling
      - Form submission
      - Accessibility
      - Form states (form-level error messaging, disabled submission buttons, synchronous/asynchronous data fetching / display, etc.)
  - **Form Patterns** - this is structured similar to "Related", a grid of use case example forms (e.g. Sign In, Payment, Multi-part, Progressive disclosure / advanced options, etc.)

SPOKES
- **Form Pattern Pages** - Page for each form use case type, which probably more closely follow the "Components Page Flow"
  - Guidance
  - Example(s)

**Comment by ericsoderberghp** [comment]
like that line of thinking
