### ISSUE TITLE
Button 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#643]
Acceptance criteria is based on alignment across the below 
- [x] Figma 
- [x] Theme
- [x] Grommet
- [x] Code Examples
- [x] Guidance

**Comment by MikeWalrath** [comment]
@ericsoderberghp I know there were some comments you had regarding the guidance for Button. Were those logged somewhere?

**Comment by ericsoderberghp** [comment]
default - the majority of Buttons on the page. Their affordance is primarily driven by their context, such as in Tabs, in Sidebar+Nav, a toolbar, the corner of a tile or card, etc.
primary - the primary call to action. There should typically be at most one primary Button on the screen. In a Form context, it signifies the action bound to the enter key that will submit the form.
secondary - When there isn’t enough context to indicate its affordance, or when it should call extra attention to itself but isn’t the primary call to action, use a secondary Button.
