### ISSUE TITLE
Header 

### ISSUE THREAD

**Issue by gregfuruiye** [hpe-design/design-system#681]
# Layer
Acceptance criteria is based on alignment across the below 
- [x] Figma 
- [x] Theme
- [ ] Grommet
- [x] Code Examples
- [x] Guidance  

## Design Proposal
![Screenshot]()

**Figma File**
https://www.figma.com/file/krgk9GTsccqOvcTm8OVzH2/HPE-Header-Component?node-id=0%3A1
## Fit Criteria
- 
## Open Items
-

**Comment by MikeWalrath** [comment]
@taysea any grommet updates associated with header?

**Comment by taysea** [comment]
No grommet updates that I found necessary @MikeWalrath
