### ISSUE TITLE
Update philosophy and principles tiles/copy

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#701]
Clarify what's in each, when to use them, and how they relate to each other.

**Comment by britt6612** [comment]
with the help of @vavalos5 ❤️

**Comment by vavalos5** [comment]
First attempt and consolidation of these two pages. I removed some headings and text as I thought it was repetitive. 

### **Philosophy**

The HPE Design System contains an open-source library of elements consisting of working code, best practices, design resources, human-centered guidelines, and a vibrant community of contributors. It enables experiences to be crafted with uncompromising integrity.

The HPE Design System is crafted upon user research and listening to customers first. 
We provide for the needs of people and their work.
 It requires a humility and position that is ready to serve others and 
We continue to relentless pursue excellence in its craft for the sake of others.

HPE Design System will advance the way people live and work.


### **Principles**

Our principles provide clear criteria for the conception, craftsmanship and creativity our brand demands and our clients deserve. They are for designers and non-designers alike, anyone authoring or authorizing any form of design on behalf of HPE.

**Innovative and Adventurous**

We are a company reborn, a new culture, and in a new space. We live in markets that ravenous and cutthroat when we are respectful and humane. We need more than technology to drive us. We need to embrace the discomfort and push to look at all avenues to stoke the fire for the next generation of tools—We must explore!

- Just start. - It is HPE’s mission to innovate.
- To conceive an idea just takes one person.
- An adventure is a shared experience. 
- The less time you spend seeking answers the better. 

**Purposeful and Useful**

Presenting a long list of features or giving the user too much choice is not the business we’re in. Usefulness should be born out of a diverse library of solutions, each honed from relentless pursuit of solving the users needs—No, “One tool to rule them all!” mentality. Every interaction should ask if this is something essential? In the end, the purpose will be ascertained by the metrics.

- Task-based experiences prioritized of data rich sifting. 
- Can we be additive, helpful, or need to make a larger shift to be useful? 
- Accentuate the user context. Usefulness is different for every user. 
- HPE provides value, not quick wins. Does the purpose serve the company?
- Lean is mean! It’s also the quickest way to learn. 

**Integrated but Composable**

To ensure every experience we define is part of a cohesive direction, it is important to ask where this product lives in the ecosystem of HPE. Not all products have to look exact to garner the confidence of customers. It is important to check how it integrates and is consumed in conjunction with other services we provide.

- Every experience talks to different set of users, but should we restrict access? 
- Designing towards a smaller set of functions opens the possibilities of utility. 
- Thinking holistically of the technology platforms can connect the dots .
- Fake it until you make it! Take a cognitive leap to push ingenuity. 

**Community**

The HPE Design System’s ethos is rooted and thrives in an environment of generosity and community. The community provides accountability, inclusive conversations and relationships that are the crucible for generating innovation. Community is the fuel for the fires of creativity and allows the Design System to expand and thrive. Best of all, it’s a great place to find support and celebrate success!

**Comment by britt6612** [comment]
Philosophy
The HPE Design System is an ethos of generosity and community. It enables experiences to be crafted with uncompromising integrity. HPE Design System will advance the way people live and work.

The HPE Design System contains an open-source library of elements consisting of working code, best practices, design resources, human-centered guidelines, and a vibrant community of contributors.

The HPE Design System is crafted upon user research and listening to customers first.

- We provide for the needs of people and their work.
- It requires a humility and position that is ready to serve others.
- We continue to relentless pursue excellence in its craft for the sake of others.

Principles
Our principles provide clear criteria for the conception, craftsmanship and creativity our brand demands and our clients deserve. They are for designers and non-designers alike, anyone authoring or authorizing any form of design on behalf of HPE.

Innovative and Adventurous
We are a company reborn, a new culture, and in a new space. We need more than technology to drive us. We need to embrace the discomfort and push to look at all avenues to stoke the fire for the next generation of tools.

- We must explore!
- It is HPE's mission to innovate.
- To conceive an idea just takes one person.
- An adventure is a shared experience.
- The less time you spend seeking answers the better.

Purposeful and Useful
Presenting a long list of features or giving the user too much choice is not the business we’re in. Every interaction should ask if this is something essential? In the end, the purpose will be ascertained by the metrics.

- Task-based experiences prioritized of data rich sifting.
- Can we be additive, helpful, or need to make a larger shift to be useful?
- Accentuate the user context. Usefulness is different for every user.
- HPE provides value, not quick wins. Does the purpose serve the company?
- Lean is mean! It’s also the quickest way to learn.

Integrated but Composable
To ensure every experience we define is part of a cohesive direction, it is important to ask where this product lives in the ecosystem of HPE. Not all products have to look exact to garner the confidence of customers. It is important to check how it integrates and is consumed in conjunction with other services we provide.

- Every experience talks to different set of users, but should we restrict access?
- Designing towards a smaller set of functions opens the possibilities of utility.
- Thinking holistically of the technology platforms can connect the dots.
- Fake it until you make it! Take a cognitive leap to push ingenuity.

Community
The HPE Design System’s ethos is rooted and thrives in an environment of generosity and community. The community provides accountability, inclusive conversations and relationships that are the crucible for generating innovation. Community is the fuel for the fires of creativity and allows the Design System to expand and thrive. Best of all, it’s a great place to find support and celebrate success!

**Comment by MikeWalrath** [comment]
@cherih were you able to take a look at this? Do you have proposal or any questions based on the above?

**Comment by cherih** [comment]
@MikeWalrath - yes, I've been working on this. 

Here's what I've done:
- browsed the current DS website to get a better feel for what's currently there
- browsed some external UX websites to get a feel for what they talk about wrt design philosophy/principles
- looked at the materials on this repo related to Voice (i.e. the PPT and prototypes)
- started jotting down ideas that I'm going to run past some folks, before fleshing them out

**Comment by MikeWalrath** [comment]
Thanks @cherih we will keep this issue open until the copy is updated on the site. Feel free to run it by folks but I would suggest posting it to this issue and the Design System Staff channel for transparency and to gather feedback quickly. Looking for your direction here.

**Comment by cherih** [comment]
@MikeWalrath - thanks for reopening this issue. I didn't mean to close it :-(. Am planning to run the copy past others for review, as you suggest.

**Comment by cherih** [comment]
### **Philosophy and Principles**
What the HPE Design System is and why we’re creating it.

**Philosophy**
The HPE Design System contains an open-source library of elements consisting of working code, best practices, design resources, human-centered guidelines, and a vibrant community of contributors. It enables experiences to be crafted with uncompromising integrity.
Key pillars of the HPE Design System are:
•	Human-centered
•	Common Design Language and UX/UI Components
•	Collaboration and Community

**Human-Centered**
The HPE Design System is crafted upon user research and listening to customers first. We provide for the needs of people and their work. We strive to create consistent and usable design patterns that will make HPE products a joy to use by customers, partners and internal HPE users.

**Common Design Language and UX/UI Components**
The HPE Design System provides a common language for designers, developers and others. This allows everyone to speak the same design language without having to translate from one language to another. This also allows for more precise specification of UX requirements.

A common set of UX/UI components for designers and developers helps to make implementation easier and more efficient. These pre-built components help provide UX consistency, localizability and accessibility.

**Collaboration and Community**
We welcome conversation and collaboration. Help us to improve the HPE Design System by working together to identify and fix missing patterns and components, or problems with existing ones. Become part of the community!

**Principles**
TBD – maybe use Edgar’s GLC design principles?

**Comment by gregfuruiye** [comment]
Thanks for working this @cherih !

Here's a few of my comments:

- Let's add in verbs to the Key Pillars. Say something like: "The Design System is built on 3 Pillars":
  - Human-centered design
  - A common design language
  - Collaboration and community
- Take out the second sentence in the Human-Centered part, while endearing, it seems to get in the way just a bit. Alternatively, make the second sentence the first and see how that flows in the paragraph.
- In a common design language:
  - Let's use 'stakeholders' in the first sentence instead of 'others'.
  - In the last sentence, remove 'help' so the sentence and our intent is a bit more direct.
- For Collaboration:
  - I wonder how we can bring people in to take a level of ownership of the Design System? So maybe adding some language that brings that to the surface by saying something like, "Collaborating with you and participating in ongoing conversation is how we can build and evolve the design system. Your voice is critical to cultivating a relationship that identifies issues and contributes to the growth and vitality of the community."

As far as priniciples go, I think we could review the one's from Edgar, but need to extract what is 'global' vs what is specific to GLC context and then merge.

**Comment by cherih** [comment]
Thank you for the review comments @gregfuruiye ! 

Here is the updated version (still need to work on Principles):

### Philosophy and Principles
What the HPE Design System is and why we’re creating it.

**Philosophy**
The HPE Design System contains an open-source library of elements consisting of working code, best practices, design resources, human-centered guidelines, and a vibrant community of contributors. It enables experiences to be crafted with uncompromising integrity.
The Design System is built on 3 Pillars:
•	Human-centered design
•	A common design language
•	Collaboration and community

**Human-Centered Design**
We provide for the needs of people and their work. The HPE Design System is crafted upon user research and listening to customers first. We strive to create consistent and usable design patterns that will make HPE products and services a joy to use by customers, partners and internal HPE users.

**Common Design Language**
The HPE Design System provides a common language for designers, developers and stakeholders. This allows everyone to speak the same design language without having to translate from one language to another. This also allows for more precise specification of UX requirements.
A common set of UX/UI components for designers and developers helps to make implementation easier and more efficient. These pre-built components provide UX consistency, localizability and accessibility.

**Collaboration and Community**
Collaborating with you and participating in ongoing conversation is how we can build and evolve the design system. Your voice is critical to cultivating a relationship that identifies issues and contributes to the growth and vitality of the community.

**Principles**
TBD – maybe use Edgar’s GLC design principles?

**Comment by gregfuruiye** [comment]
@cherih 
Here's a few thoughts about principles. For the Design System website, I think they must be broad enough to encompass the global HPE experience. They also need to be broken down into a title, simple 2-3 sentence paragraph and a set of 3-5 bullets. It'd be great to see the philosophy broken up into that type of format as well.

Let's keep the principles where they are and then have @MikeWalrath add time for us to talk with Chris and Eric about merging stuff in.

**Comment by cherih** [comment]
Here are some updated Principles to go with the Philosophy above. Review comments on the combined content are welcome.

### Principles
Our principles provide clear criteria for the concepts, craftsmanship and creativity our brand demands and our clients deserve. They are for designers and non-designers alike, anyone authoring or authorizing any form of design on behalf of HPE. Designs created using these principles will be innovative and adventurous, purposeful and useful, and integrated but composable.

**Focus on the experience**
Focus on the user experience (UX).
•	Consider the use cases
•	Simplify the end-to-end experience, making it elegant, intuitive and easy
•	Express creativity by empathizing with the user

**Simplify**
Be as simple as possible, but no simpler. Only add things, if they are really needed.
•	Reduce visual and cognitive overload
•	Understand “why” things are needed in your design
•	Design for the mainstream use cases, yet provide ways to accomplish less frequent tasks

**Be Intuitive**
Create designs that are easy to understand and use.
•	Make use of affordance and common user interface paradigms 
•	Use consistent patterns and terminology within your design and across designs
•	Create self-documenting designs to minimize the need to refer to online help and other user documents

**Lead people to success**
Present paths that guide customers to accomplish the task or goal they are trying to accomplish. It is the right thing to do and it results in happy customers.

•	Show only choices and fields that apply to the current context
•	Organize choices and fields with most common/reasonable first
•	Reveal additional fields only when they apply
•	Provide appropriate safeguards to protect the customer and HPE from mistakes or unintentional actions

**Comment by cherih** [comment]
Here are the combined Philosophy and Principles for final review.

Philosophy and Principles
What the HPE Design System is and why we’re creating it.

Philosophy
The HPE Design System contains an open-source library of elements consisting of working code, best practices, design resources, human-centered guidelines, and a vibrant community of contributors. It enables experiences to be crafted with uncompromising integrity.

The Design System is built on 3 Pillars:
• Human-centered design
• A common design language
• Collaboration and community

Human-Centered Design
We provide for the needs of people and their work. The HPE Design System is crafted upon user research and listening to customers first. We strive to create consistent and usable design patterns that will make HPE products and services a joy to use by customers, partners and internal HPE users.

Common Design Language
The HPE Design System provides a common language for designers, developers and stakeholders. This allows everyone to speak the same design language without having to translate from one language to another. This also allows for more precise specification of UX requirements.

A common set of UX/UI components for designers and developers helps to make implementation easier and more efficient. These pre-built components provide UX consistency, localizability and accessibility.

Collaboration and Community
Collaborating with you and participating in ongoing conversation is how we can build and evolve the design system. Your voice is critical to cultivating a relationship that identifies issues and contributes to the growth and vitality of the community.

**Comment by cherih** [comment]
Thanks to Taylor for updating the DS website with this copy!

I verified that the updates look as expected.
