### ISSUE TITLE
Home page first 5 cards

### ISSUE THREAD

**Issue by halocline** [hpe-design/design-system#710]
[Preview](https://deploy-preview-811--keen-mayer-a86c8b.netlify.app/)

Decide on the initial top 5 (poker hand) cards we want to see on the home page.
Make it so.

**Comment by halocline** [comment]
WARNING: This following is somewhat stream of conscious and incomplete. However, documenting it so I can come back and edit later and/or perhaps it stimulates other folks' thoughts.

**My thoughts on card order**

Card order for each content hub should support presenting/promoting the most utilitarian content for the visitor.

Those visitors may be:
- **First time visitors** (want: what is this? how does it benefit me? how does it benefit HPE customers? how do I get started?)
  - Subtypes: (Designer, Developer, Others?)
- **Returning visitors** (want: I have an objective and I am hoping to find guidance / resource to help me achieve my objective. I am also familiar with the site's purpose, types of content I can expect, and utility)
  - Subtypes: (Designer, Developer, Others?)

Our Goal:
- First time visitors
  - Answers: what, how benefits, how get started / use
  - Get them to the point in which they are familiar with the site's purpose, types of content, and utility
- Return visitors
  - Discover their objective and get them routed to the answer as efficiently as possible

Depending on audience, the card order utility likely shifts. Also, within an audience, there are likely different preferences and learning modalities. Therefore, we should consider a mix of the following: 
- Featured content which we know helps orient new visitors (or our best guess in data gathering phases)
- Most frequently used 
- Something splashy serving as "eye candy" or "shiny object" that draws the visitor into the site in a browsing/discovering mental mode

**Home Page**
As a first time visitor to the Design System site, I have :
  - What is the design system

Need for a Getting Started card? --> Serves as About/Introduction, hub for routing to Designer Guidance, Developer Guidance, Tutorial on (how to use the site, included features, recommendations, etc.).

Featured content (Getting Started, Designer Guidance, Developer Guidance)
Most frequently used (Patterns, Page Layouts, Forms, Tables, Lists, Grid, Box)
Shiny object (Dashboards, Data Visualization)


**Foundation**

**Components**

**Templates**

**Extend**

**Comment by ericsoderberghp** [comment]
Agreed on the variance and therefore the mixture aspect.

I like the idea of a "start here" card that serves as an overall introduction. I'll add an issue for that.

Until that lands, on the home page I like the idea of picking one card per suit as the best card for that suit to start with. That illustrates variety of content.

For the Foundation landing page, I'd lean towards an order of reading, as if it were a book.

For the Components landing page, I'd lean towards either pure alphabetical or follow the grommet groupings.

For the Templates and Extend landing pages, I'd lean towards most frequently used.

**Comment by taysea** [comment]
^^ I like this line of thinking and agree with this proposal. Any thoughts on what that book order would be for Foundation section? 

Some of the cards in that section are could "context setters", such as "Human Centered" or "Philosophy" and maybe those would make sense to come first in the story. But that pushes the cards with tangible resources "Color" and "Typography" much farther down.

**Comment by halocline** [comment]
**Proposed Order** based on discussion thus far:

**Home** (representative of variety across card suits for first 10, then by category sorts below)
- Designer Guidance, Forms, Header, Human Centered, Developer Guidance, Button, Navigation, Icons, Search, Typography, ...

**Foundation** (by category)
- Group by foundation category (Philosophy, Assets)
  - Philosophy (by book chapter -- what we care about, then how we do it) --> Philosophy, Human Centered, Accessibility, Principles, ...
  - Assets (by book chapter) --> Brand, Color, Typography, Icons, ...

**Components** (by category)
- Group by component function (layouts, type, controls, inputs, etc.), then alphabetical within

**Templates** (by availability, then by frequency)
- Page Layouts (not yet available), Forms, Navigation, Lists, Dashboards, ...

**Extend** (by availability, then by frequency)
- Designer Guidance, Developer Guidance, ...

**Comment by gregfuruiye** [comment]
If you'd like to watch how some folks engage with the site, just to explore a bit, you can view some video content on UserZoom from our recent [usability study](https://analytics.manager2.userzoom.com/5834/11d9abee-647e-ea11-aa61-bda55d26a69b/videos/session-replay)

In particular, are these participant IDs when you go to the videos. You'll want to click on the video for Task 'T7':

- C5834S53_45
- C5834S53_87
- C5834S53_68
--
