### ISSUE TITLE
Expand Designer Guidance

### ISSUE THREAD

**Issue by taysea** [hpe-design/design-system#712]

**Comment by vavalos5** [comment]
I think I would want to see the Design System Library header and info. below the "Designer Guidance" header and before the "Let's Get Started" header

In the "Designer Guidence" I added some nouns to add more specification:

The HPE Design System sticker sheet provides a clear foundation for designing HPE applications. The sticker sheet provides an overview of text styles, colors, icons and components contained within the Design System library.

**Comment by vavalos5** [comment]
We could also add a section after "Joining the HPE Design System Figma team" that talks about familiarizing yourself with the contents (HPE Sticker Sheet) before creating anything on Figma.

1. Familiarize yourself with colors
2. Grid 
3. Typography
4. Icons
5. Components

Etc...

**Comment by taysea** [comment]
> I think I would want to see the Design System Library header and info. below the "Designer Guidance" header and before the "Let's Get Started" header

What is the header and info you're talking about? Could you elaborate a little
> 
> In the "Designer Guidence" I added some nouns to add more specification:
> 
> The HPE Design System sticker sheet provides a clear foundation for designing HPE applications. The sticker sheet provides an overview of text styles, colors, icons and components contained within the Design System library.

**Comment by vavalos5** [comment]
@taysea I meant to say heading** not header. 

So, I'd like to see the "Design System Library" heading that is towards the bottom of the page to be moved up right below the "Designer Guidance" heading. Let me know if you want to connect to discuss.

**Comment by taysea** [comment]
Thanks for the feedback Vicky, I'm going to take a pass at incorporating this in.

**Comment by taysea** [comment]
Closed by #748
