### ISSUE TITLE
CheckBoxGroup

### ISSUE THREAD

**Issue by ericsoderberghp** [hpe-design/design-system#743]
# CheckBoxGroup
A group of CheckBoxes used within a Form context. Somewhat equivalent to a Select where multiple options can be selected.

Acceptance criteria is based on alignment across the below 
- [x] Figma https://www.figma.com/file/zkQOQRUt8frxiSo67kTkfE/HPE-Checkbox-Group-Component?node-id=64%3A240
- [x] Theme
- [x] Grommet
- [x] Code Examples
- [x] Guidance  

## Guidance starter

- Discuss when to use CheckBoxGroup vs. Select with multiple.
- Discuss when to use multiple single CheckBoxes vs. a CheckBoxGroup.

**Comment by saggiemilva** [comment]
Here's my first pass at Checkbox Group Guidance. I will need some help from dev to fill out the _Create(How)_ section.

### Checkbox Group 

**Create(How):** 
- 
-   
- 
- 

**Best Practices(Why):** 
- Checkbox Group should be used to select zero or more of options from a list. 
- In a Checkbox Group, options are Independent from one another. 
- Settings changed by checkboxes should not take effect until the user clicks to proceed. 
- It is recommended to have only 10 or fewer options in a Checkbox Group. 
- Use multiple Checkbox Groups if necessary. 

**Conventions(Do):** 
- Always label Checkbox Groups with short and concise labels. 
- Give every Checkbox in the group a short, but descriptive value. 
- Clearly separate Checkbox Groups from other groups on the same page. 
- Organize Checkboxes in a logical order by grouping related options. 
- Consider placing most common options first in the group. 
 
**Usage(Don't):** 
- Don’t align Checkboxes horizontally in a group. 
- Refrain from using Checkbox Group when only one item can be selected from a list.  
- Checkboxes should not be used as action buttons that automatically make something happen.

**Comment by ShimiSun** [comment]
Looks great!
Regarding:
> Checkboxes should not be used as action buttons that automatically make something happen.

I do see a use case in a form when some fields are hidden and CheckBox enables other fields to open, see for example:
https://storybook.grommet.io/?path=/story/form--dynamic-fields

I'm wondering if that statement could be refined or moved to the context of CheckBox itself rather than CheckBoxGroup.
