### ISSUE TITLE
Not possible to right-justify a checkbox; wants to take up entire row

### ISSUE THREAD

**Issue by ecircenis** [hpe-design/design-system#762]
### Is this issue related to the design system core library or design system website?

design-system-core

### Expected Behavior
It should be possible to create a checkbox as a discrete component next to other components and have it respect gap and justification.

### Actual Behavior

A checkbox seems to want to take over all available space. (this also applies to toggles)

### URL, screen shot, or CodeSandbox exhibiting the issue

Here's an example from a grommet designer design.  You can see that the containing box specifies right justification, but the checkbox is still left justified.  My intent was to butt the checkbox against the button.
![image](https://user-images.githubusercontent.com/17883783/81424846-cd1f2d00-9113-11ea-8fc5-d08bebc37762.png)

Hovering over the checkbox, I can see that it is actually right justified, but is taking up all available space making it appear left justified:
![image](https://user-images.githubusercontent.com/17883783/81425011-09eb2400-9114-11ea-8c4b-7b44bb07fff6.png)

### Your Environment

Using grommet designer with this theme:
https://grommet.github.io/grommet-theme-hpe/grommet-theme-hpe-next.min.js
Chrome
Windows 10

**Comment by britt6612** [comment]
@ecircenis Thank you for pointing out this issue. 

https://designer.grommet.io/checkbox?id=HPE-design-system-brittany-archibeque-hpe-com
I recreated what you had in your preview, in the updated designer. You should now be able to right align the checkbox. The width of checkbox was taking up the whole space this should be fixed now with the updated hpe theme

**Comment by halocline** [comment]
@ecircenis Are you now able right-justify the checkbox as desired?

@britt6612 @MikeWalrath Can this issue be closed?

**Comment by MikeWalrath** [comment]
Thank @halocline lets verify with @ecircenis first to close the feedback loop and then we can close 👍

**Comment by ecircenis** [comment]
Yes @halocline @MikeWalrath, it is working correctly now. Thanks!

**Comment by MikeWalrath** [comment]
Thank you @ecircenis
