### ISSUE TITLE
Page Layouts exploration

### ISSUE THREAD

**Issue by ericsoderberghp** [hpe-design/design-system#766]
To start with, add a card under templates for page layouts. This is just a placeholder to start with to indicate that it's on our radar and content will be coming.

Explore the different types of layouts we want to cover.
Include responsive aspects.

Create a separate issue in the backlog for each type of layout for subsequent work.

**Comment by MikeWalrath** [comment]
Initial ideas to explore
- Table centric
- List centric
- Grid centric
- Document centric
