### ISSUE TITLE
Header link to Figma Update

### ISSUE THREAD

**Issue by gregfuruiye** [hpe-design/design-system#780]
### Is this issue related to the design system core library or design system website?

design-system-website

### Expected Behavior
The link to the figma file for header should point to https://www.figma.com/file/krgk9GTsccqOvcTm8OVzH2/HPE-Header-Component?node-id=0%3A2

### Actual Behavior
The link is pointing to the older version https://www.figma.com/file/FwJr2zaT8Rr7RyIKLm7Lvg/hpe-design-system-library-headers?node-id=0%3A1

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Design System version:
- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by halocline** [comment]
@gregfuruiye URL updated. Here's a preview link: https://deploy-preview-781--keen-mayer-a86c8b.netlify.app/components/header

**Comment by gregfuruiye** [comment]
Looks great, thanks @halocline !
