### ISSUE TITLE
1st announce share-out meeting

### ISSUE THREAD

**Issue by ericsoderberghp** [hpe-design/design-system#783]
Schedule and deliver a zoom meeting to give an overview of where we are with the design system. Advertise on the #hpe-design-system channel.
30 minutes long.
Suggested outline:
- 5m welcome and intro
- 5m review the site, structure, organization
- 5m review figma resources
- 5m review feedback channels
- 5m review roadmap
- 5m Q/A

**Comment by gregfuruiye** [comment]
I'd like to create an outline/script so we can stay on task during those 5m bouts of content. Feel free to add, remove, edit:

- Welcome and Intro - 5 min
  - Greg hosts
  - Include Design Team graphic with images
  - Design System intent (why it was created)
- Site Overview - 5 min
  - Structure - the big parts
  - Navigation - how to get places
  - Organization - how to find what you need (behavioral logic)
- Figma Resources - 5 min
  - How to get to Figma
  - HPE Organization, Teams, Projects
  - Component Libraries - enabling, using
  - Component Files - viewing, using
  - Docs? - transition to seeing the code bits?
- Roadmap 🔮- 5 min
  - Components
  - Templates
  - Patterns/Behaviors
  - Community Events/Engagement
- Feedback Channels - 5 min
- Q & A

**Comment by jeyathilak** [comment]
Would like to attend this zoom meeting to get an overview of HPE Design system. Who do I contact?

**Comment by MikeWalrath** [comment]
@jeyathilak thank you for the interest. We will be scheduling the meeting/presentation before the end of the day. We will be promoting it on the [hpe-design-system ](https://grommet.slack.com/archives/C04LMJWQT)channel so anyone who has interest can join. I'll follow up with you to make sure you have the invite. Thanks for reaching out! 👍
