### ISSUE TITLE
List template exploration

### ISSUE THREAD

**Issue by ericsoderberghp** [hpe-design/design-system#799]
Artifacts - what should be delivered

- [ ] publish 3-10 screenshots or URLs showing existing list variations on existing sites
- [ ] create 2-3 initial design direction alternatives, rough, <1day per
- [ ] add notes in this issue about findings and recommendations
- [ ] conduct a review meeting with design system team
- [ ] create additional backlog items

Aspects - what should be considered

Variations on list item content:
- name or id
- icon
- status
- secondary content, perhaps a timestamp

Variations on related descriptors and interactions
- heading naming what the list contains, probably tied to navigation link names
- additional descriptive text
- basic search interaction
- detailed filtering
- sorting
- summary of number of items due to any filtering, for example: "20 out of 1000"
- control to add an item
- hover indication for navigation
- multi-select for batch actions

Also include responsive and accessible aspects

This issue is for the Figma work in this area. Other issues will be added for the design system site and any theme or grommet work later.

Some examples of user stories:

- As an HPE Green Lake administrator, I need to narrow the list of quotes to find the set of quotes that are in a state that I need to attend to so I can work on fulfilling them.

- As an HPE Green Lake account rep, I need to find out the status of one of my customer's quotes so I can update the customer on the quote's status. All I have is the name of the customer and the date it was requested.

- As an Aruba administrator, I need to determine how many devices I have of a particular model as Aruba has indicated that that model is being sunsetted and I need to start working on upgrading to new devices.

**Comment by saggiemilva** [comment]
Here is the link to the first pass at list guidance: 
https://github.com/hpe-design/design-system/issues/376#issuecomment-626829288

**Comment by MikeWalrath** [comment]
Discussed as a team and no other work is needed within the "exploration" issue. We will create subsequent issues for the preview.
https://www.figma.com/file/tMYTr17r6hhGajSlNRiPje/HPE-List-Component?node-id=0%3A1
