### ISSUE TITLE
Cards template exploration

### ISSUE THREAD

**Issue by ericsoderberghp** [hpe-design/design-system#801]
Artifacts - what should be delivered

- [ ] publish 3-10 screenshots or URLs showing existing card variations on existing sites
- [ ] create 2-3 initial design direction alternatives, rough, <1day per
- [ ] add notes in this issue about findings and recommendations
- [ ] conduct a review meeting with design system team
- [ ] create additional backlog items

Aspects - what should be considered

Variations on card item content:
- name or id
- icon
- graphic image
- status
- secondary content, perhaps a timestamp
- a big number with units
- a single data visualization, a meter or chart

Variations on related descriptors and interactions
- heading naming what the set of cards contains, probably tied to navigation link names
- additional descriptive text
- basic search interaction
- detailed filtering
- sorting
- summary of number of items due to any filtering, for example: "20 out of 1000"
- control to add an item
- hover indication for navigation
- multi-select for batch actions

Also include responsive and accessible aspects.
In addition to mobile resolutions, address wide screens. For instance, is there a maximum width?

**Comment by MikeWalrath** [comment]
Provided feedback on the initial concept. We will take the next step and create a preview for the Card template that we can iterate on.
