### ISSUE TITLE
Basic DatePicker Calendar Component

### ISSUE THREAD

**Issue by jeyathilak** [hpe-design/design-system#806]
### Is this issue related to the design system core library or design system website?
design-system-core

### URL, screen shot, or CodeSandbox exhibiting the issue
Something similar to this:
https://stackblitz.com/angular/mnqdlnjpbex?file=src%2Fapp%2Fdatepicker-overview-example.ts

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Design System version:
- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

- [x] Figma Design

- [x] Guidance Text

**Comment by ericsoderberghp** [comment]
Hopefully, this will be available this week: https://github.com/grommet/grommet/pull/4198

**Comment by vavalos5** [comment]
Figma file can be found here: https://www.figma.com/file/Mf9if6zyGETTWW5b9PsYNQ/HPE-Date-Input-Component?node-id=0%3A1

**Comment by vavalos5** [comment]
First pass at date input content. Not entirely sure what to write for guidance. 

**Date Input**
Date Input is a widget which allows users to select a date or a range of dates from a calendar.

**Guidance**
The date input is used when …

**When using Date Input, you should:**

- Use a label when appropriate
- Correctly format to reduce mistakes such as having the caller specify the appropriate date format for the locale the user is in. For example, in the U.S. dates are formatted as ‘mm/dd/yyyy’ whereas in other countries, such as Europe it might be ‘dd/mm/yyyy’.


**Usage**
Use the date input component when you want the user to assign past, present or future date(s).


**Variants**
Date Input - This date input can used to pick one day or a range of dates, depending on your use case. Concise labels should be included on this variant to let the user know what to do.

Date Input / Dual - The dual date input is another great option to let your users pick a range of dates while visually seeing two months side-by-side.
