### ISSUE TITLE
Add "indeterminate" (and "toggle" ?) state to CheckBoxGroup

### ISSUE THREAD

**Issue by taysea** [hpe-design/design-system#809]
On the first pass of implementation, indeterminate and toggle haven't been incorporated. It seems fitting that indeterminate would be a valid state, but would be also want to allow a group of toggles?

Seems like the implementation would be that you'd supply the `options` prop with an array of objects such as 

```
options = [
{ label: 'Option 1', indeterminate: true}
OR
{ label: 'Option 1', toggle: true}
...
]
```
Currently, it seems like it renders the toggle but the clicking/unclicking doesn't follow through correctly

**Comment by ShimiSun** [comment]
I would like to see designs and use cases for toggled CheckBoxGroup before attempting to support it.

**Comment by saggiemilva** [comment]
I do not see a need to have a toggle CheckBoxGroup. If someone was using multiple toggles it would be recommended they use them as individual elements. However, I do agree that there should be some variation of CheckboxGroup that has a parent, child element resulting in an indeterminate.

**Comment by MikeWalrath** [comment]
Closing for now. If there is a use case for an intermediate check we will re-address
