### ISSUE TITLE
Align theme to Figma for border width, border radius, FormField margin

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#818]
Related to #746 

In addition to aligning the theme's border width and border radius to Figma, a tweak to FormField to allow the theme to specify margin around the input [is needed in Grommet](https://github.com/grommet/grommet-theme-hpe/pull/69#discussion_r424779815).

**Background** 
Currently, margin can be added to the entire component, label, help, info, or error text. However, in scenarios where margin is set on label and help text, this adds unwanted space between label and help, deviating from [designs which call for no space between label/help](https://www.figma.com/file/fZJdRcNrvZ1JjdPRYHpFFU/HPE-Select-Component?node-id=103%3A140) -- only between text and input.

- [x] Correct spacing between Description/help text and input
  - [x] Add ability for `formField.content.margin` to be specified in Grommet
    - [x] PR submitted https://github.com/grommet/grommet/pull/4140
  - [x] Implement changes in `grommet-theme-hpe` ([PR submitted](https://github.com/grommet/grommet-theme-hpe/pull/69))
- [x] Confirm border width, border radii, and FormField input margin all in alignment with Figma

**Comment by halocline** [comment]
Discussion for devs on margin approaches to FormField in Grommet: https://docs.google.com/drawings/d/19X7TJ1nqiW_r3prBLWLTVazPUJnwSj7JJdTNesL_5WY/edit?usp=sharing

**Comment by halocline** [comment]
Grommet PR submitted: https://github.com/grommet/grommet/pull/4140

**Comment by halocline** [comment]
Updated PR applying newly available theme props from Grommet. https://github.com/grommet/grommet-theme-hpe/pull/69
