### ISSUE TITLE
Assess padding/text placement issues in button and select in Designer

### ISSUE THREAD

**Issue by taysea** [hpe-design/design-system#828]
Some issues regarding Button and Select were noted in the designer. Theme and grommet changes need to be reviewed to see if any recent changes caused these effects. Images below of issues being noted:
![image (3)](https://user-images.githubusercontent.com/12522275/83552746-1f5b3000-a4bf-11ea-8163-9c0a75720d85.png)
![image (2)](https://user-images.githubusercontent.com/12522275/83552748-1ff3c680-a4bf-11ea-8e5d-6d4debf7dd4a.png)
![image (1)](https://user-images.githubusercontent.com/12522275/83552751-208c5d00-a4bf-11ea-95fc-1149857ef44a.png)

**Comment by halocline** [comment]
Select drop is getting  browser's focus border as well:
![Screen Shot 2020-06-02 at 11 51 55 AM](https://user-images.githubusercontent.com/1756948/83552829-9d233980-a4c7-11ea-99e8-00d85fb67d68.png)
![Screen Shot 2020-06-02 at 11 54 25 AM](https://user-images.githubusercontent.com/1756948/83553035-deb3e480-a4c7-11ea-97b3-3cec2ab6998c.png)

**Comment by taysea** [comment]
> Select drop is getting browser's focus border as well:
> ![Screen Shot 2020-06-02 at 11 51 55 AM](https://user-images.githubusercontent.com/1756948/83552829-9d233980-a4c7-11ea-99e8-00d85fb67d68.png)
> ![Screen Shot 2020-06-02 at 11 54 25 AM](https://user-images.githubusercontent.com/1756948/83553035-deb3e480-a4c7-11ea-97b3-3cec2ab6998c.png)

Wonder if this change is related to whatever is causing this issue as well: https://github.com/hpe-design/design-system/issues/829

**Comment by halocline** [comment]
> I think some of the shift could be due to the new font-format. In this video, notice the slight shift in the button text in the navigation. I think this is contributing to the issues Edgar and Jens are pointing out. The "left tab" is the new font format of woff2 (text is slightly higher).
> ![lineheight](https://user-images.githubusercontent.com/12522275/83556974-af9c7380-a4c5-11ea-9138-ab6199293475.gif)
> 
> In the designer links shared by Edgar and Jens, the text placement is not as drastic as their screenshots (regardless of what browser I'm using), but I am able to notice a subtle difference.

I feel like I recall hearing that the new font did have adjustments to line-height. I may notice a bit more exaggeration in FF than Chrome or Safari.

**Comment by taysea** [comment]
![font-formats](https://user-images.githubusercontent.com/12522275/84059439-76ee1580-a96f-11ea-98a4-9e4d7d91845f.gif)
Toggling between a designer file provided by jens. The tab labelled 'Taylor - ...' has the hpe theme prior to the new woff2 format, and the other tab is with the new woff2 format. The whole page shifts as we toggle between tabs because the placement of the text in a line seems to be different between woff2 and the prior woff format. I think this is the root of the issues people are seeing.

**Comment by halocline** [comment]
> Toggling between a designer file provided by jens. The tab labelled 'Taylor - ...' has the hpe theme prior to the new woff2 format, and the other tab is with the new woff2 format. The whole page shifts as we toggle between tabs because the placement of the text in a line seems to be different between woff2 and the prior woff format. I think this is the root of the issues people are seeing.

Agree that the shift is due to font files. The difference is caused by MetricHPEXS (new) vs. MetricHPE (prior) as opposed to .woff vs. .woff2.

Here is a good screenshot and context: https://github.com/hpe-design/design-system/issues/506#issuecomment-638965428
![metrichpexs-comparo](https://user-images.githubusercontent.com/1753301/83785104-ac2ff600-a645-11ea-8614-870739cbc5e8.png)

**Comment by taysea** [comment]
Gotcha, yes you are right. It is not an issue of woff vs woff2, but the shift from Metric HPE to MetricHPEXS.

Oddly, based on the shift of the fonts it seems like the new font is shifting in a direction counter to what I'd expect. The older MetricHPE font (with extra space on the bottom) had been aligning properly, but the new HPEXS version seems to shift all text upward (especially in cases where text has a descender, such as "g") as if the bottom space in the old font already was leaving room for descenders.

I think a 15-30min discussion would be sufficient to iron out the discrepancy here and decide what we want to do with the font file.
