### ISSUE TITLE
Default button blocking hover styling from occurring on TextInput/Select options because of `plain`

### ISSUE THREAD

**Issue by taysea** [hpe-design/design-system#834]
Being tracked on grommet here: https://github.com/grommet/grommet/issues/4142

**Comment by taysea** [comment]
One more note about Button:
- in select, the drop down options have a height of 34px, but the designs call for 36px

I feel like this is a combination of the `plain` being applied to the button and maybe something else we're doing in the theme? just something to look at while we explore the above issue to make sure the proper dimensions will be able to be achieved.

**Comment by ericsoderberghp** [comment]
I believe this has been addressed with the latest grommet + HPE theme changes. Can you verify?

**Comment by taysea** [comment]
This has been resolved. Closing this issue.
