### ISSUE TITLE
Increase visibility to the component variations

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#859]
Looking for different solutions on how we can increase the visibility of the variations on the component pages. 

https://publisher.grommet.io/recommendations?id=2020-Q2-HPE-Design-System-Study-greg-furuiye-hpe-com 
Variations were missed below the fold
- Surface content availability through content cues
- 'Lift' variations providing cues in the primary content

**Comment by taysea** [comment]
I know we had been pushing for a single column design for the pages, but I find this approach very effective for understanding page structure. This is taken from material ui docs where each is a quick link to that page section:
<img width="1435" alt="Screen Shot 2020-06-17 at 2 46 19 PM" src="https://user-images.githubusercontent.com/12522275/84954011-74936600-b0a9-11ea-93cf-206f7b0a3908.png">
