### ISSUE TITLE
Review Placeholder Text color

### ISSUE THREAD

**Issue by gregfuruiye** [hpe-design/design-system#894]
Placeholder text should be discernable in the UI. It is defined in Figma color styles and components, but not showing up in the theme.

Figma Select component:
https://www.figma.com/file/fZJdRcNrvZ1JjdPRYHpFFU/HPE-Select-Component?node-id=0%3A1

Figma Typography styles (includes form/placeholder text style):
https://www.figma.com/file/oJhw3JqMemtbwWjlLPWW5O/HPE-Typography-Styles?node-id=0%3A1

### Deliverables
- [ ] update grommet-theme-hpe as needed

**Comment by taysea** [comment]
The grommet PR has been merged. Closing this issue now.
