### ISSUE TITLE
HPE font not displaying properly

### ISSUE THREAD

**Issue by taysea** [hpe-design/design-system#895]
### Is this issue related to the design system core library or design system website?

design system website
### Expected Behavior

The site should use HPEXS font
### Actual Behavior

The generic sans-serif font is being pulled in

### URL, screen shot, or CodeSandbox exhibiting the issue

<img width="1477" alt="Screen Shot 2020-06-12 at 10 08 22 AM" src="https://user-images.githubusercontent.com/12522275/84532337-ef6c1380-ac9a-11ea-9223-9bc7301dd04b.png">
<img width="926" alt="Screen Shot 2020-06-12 at 10 08 16 AM" src="https://user-images.githubusercontent.com/12522275/84532342-f2670400-ac9a-11ea-9346-65c1e122d88a.png">

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Design System version:
- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by halocline** [comment]
![Screen Shot 2020-06-12 at 11 56 43 AM](https://user-images.githubusercontent.com/1756948/84532680-e29fed80-aca3-11ea-9424-93b4bf577832.png)
![Screen Shot 2020-06-12 at 11 56 32 AM](https://user-images.githubusercontent.com/1756948/84532686-e5024780-aca3-11ea-93ab-9789d479e164.png)

**Findings**
When uploading new versions of the MetricHPEXS-Bold fonts, CloudFront had cached a version of those files where the CORS policy was incorrectly set. The settings were updated in S3, however the updated version of the file hadn't yet replaced CloudFront's cached version (up to 24 hour cycle).

**Resolution**
- Confirmed S3 bucket CORS settings were correct: 
![Screen Shot 2020-06-12 at 12 02 58 PM](https://user-images.githubusercontent.com/1756948/84533093-b042c000-aca4-11ea-8323-f178d3d0b00c.png)
- Confirmed CloudFront General & Behavior settings
- Invalidated CloudFront cache for MetricHPEXS-Bold.woff & MetricHPEXS-Bold.woff2 by implementing an invalidation rule which forces CloudFront to clear its caches for the specified files/directories. In this case, the rule was:
![Screen Shot 2020-06-12 at 12 07 19 PM](https://user-images.githubusercontent.com/1756948/84533402-4d055d80-aca5-11ea-9316-957c989fc73e.png)
