### ISSUE TITLE
Complete Grommet components (Nav, header, footer) 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#90]

**Comment by ShimiSun** [comment]
https://github.com/grommet/grommet/pull/3598
https://github.com/grommet/grommet/pull/3594
https://github.com/grommet/grommet/pull/3597

**Comment by ShimiSun** [comment]
https://github.com/grommet/grommet-site/pull/131
https://github.com/grommet/grommet-site/pull/130
https://github.com/grommet/grommet-site/pull/132
