### ISSUE TITLE
Resolve nested scroll coming from main within Page Layout template

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#924]
Example provided by Chris within the design system staff channel. 
https://hpe.slack.com/archives/GPPLUK6LR/p1592841540001500

**Comment by taysea** [comment]
I believe scrolling is appearing as intended. We want the scrolling because in these examples we want to demonstrate the scrolling behavior of fixed vs scrollable regions. For example, sidebar is fixed but main and header scroll. I think we can close this issue.

**Comment by MikeWalrath** [comment]
@L0ZZI are you ok with this approach and closing this issue?

**Comment by MikeWalrath** [comment]
Closing for now. We will revisit if needed based on feedback and research.
