### ISSUE TITLE
add validation examples and guidance to Forms

### ISSUE THREAD

**Issue by ericsoderberghp** [hpe-design/design-system#928]
There currently isn't any visual example or guidance for how validation works for forms.

### Deliverables
- [x] update figma with examples.
- [ ] update design system site with additional guidance.

expected to take < 1 day

**Comment by lorbritton** [comment]
We need some guidance on whether or not to mark required fields in forms. The current standard marks only optional fields, but the best practice for accessibility is to denote required fields with a symbol (like the standard *). There's an example in Storybook that adds the * after the form is submitted, which seems kind of odd/uncommon.

**Comment by halocline** [comment]
Need guidance for form level validation (e.g. perspective on disabling buttons until all fields validated, server response validations) as well as field level validation (e.g. real-time field level feedback as data is entered)

**Comment by MikeWalrath** [comment]
Form Validation 
- Enabled submit button 
- After clicking submit field validation will occur 
- Optional vs required 
    - Add asterisk to the theme for required field set
    - No action required for optional

**Comment by ericsoderberghp** [comment]
From a discussion with GreenLake designers:

If a form has fields that can be hidden, such as in an accordion or via a progressive disclosure toggle, when the form is validated, if there are any errors with the fields that are hidden, those fields should be made visible, so the user has visibility into the errors.

**Comment by gregfuruiye** [comment]
Optional/Required Fields Issue is tracked in #930

**Comment by gregfuruiye** [comment]
Current examples for review are now in the [Figma File](https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=1965%3A2332)

**Comment by ericsoderberghp** [comment]
I see the required field aspects, I don't see the other validation related aspects yet.

**Comment by gregfuruiye** [comment]
I'll pull these into the "Finished" page on the Figma file.

**Comment by gregfuruiye** [comment]
just updated form validation onto the 'Finished' page in Figma:

[https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=0%3A1](https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=0%3A1)
