### ISSUE TITLE
Optional and Required Field Guidance for Forms

### ISSUE THREAD

**Issue by lorbritton** [hpe-design/design-system#930]
We need some guidance on whether or not to mark required fields in forms. The current standard marks only optional fields, but the best practice for accessibility is to denote required fields with a symbol (like the standard *). There's an example in Storybook that adds the * after the form is submitted, which seems kind of odd/uncommon.

**Comment by ericsoderberghp** [comment]
### Deliverables
- [ ] update design system site with additional guidance.

expected to take < 1 day

**Comment by gregfuruiye** [comment]
As documented in [Edgar's OneNote](https://hpe.sharepoint.com/teams/hpe-design/_layouts/15/Doc.aspx?sourcedoc={a99eae23-950c-45af-95e8-e31766899ceb}&action=edit&wd=target%28ST%20-%20GreenLake%20HC.one%7Cd6469e82-6db5-4612-8f8f-0d6267f2f101%2FCore%20Tenets%20%5C%2F%20NFRs%7C36878fc0-03b5-4964-b712-fe956fb8f976%2F%29)
How to decorate required/optional form fields? 

- Use asterisk (same color as label) in the field label for required fields. 
- Modify HPE theme to add the asterisk automatically. 
- No need to explain what the asterisk means. 
- No need to decorate optional fields. 

[Figma File for Forms](https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=0%3A1)

**Comment by gregfuruiye** [comment]
We are proposing that required fields are not needed to be noted on sign in/up forms. All other 'standard' forms would use the asterisk to indicate required fields.
