### ISSUE TITLE
Align Theme color names/capabilities and Figma color names 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#932]
Naming conventions within the two are not aligned and causing confusion.

**Comment by gregfuruiye** [comment]
Here is the image in Slack from Raha:

https://hpe.slack.com/files/UJH8BN9BP/F015X94G61K/image.png?origin_team=TH0KDGMRB&origin_channel=C04LMJWQT

**Comment by ericsoderberghp** [comment]
Is there a specific proposal for how this would be resolved. I think a key difference is that grommet has structure to color names. You don't use "green light", you use "green" and in a light background context, it will use `green.light`.

**Comment by gregfuruiye** [comment]
Here's the Figma file were work to reconcile colors is being conducted:
https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/HPE-Color-Styles?node-id=1680%3A418

**Comment by gregfuruiye** [comment]
I'm in the process of updating the Figma Color Styles to more closely align to our code (and still make sense with designers). However, there are some other areas in the code to explore:

- Update code where 'disabled-text': ‘text-weak’
- Update code where 'status-disabled': 'text-weak'  *Where is 'status-disabled' used if we have 'status-unknown' ?
- In Figma, we also have a color style "Validation, Disabled" which looks to be a fill color with transparency, but not sure where this is being used (on button?).
- add the following validation colors:
  - 'validation-warning': { light: '#FFBC443D' , dark: '#9B63105C' }
  - 'validation-ok': { light: '#17EBA03D' , dark: '#00856759 }

Tracking this in a rough Figma File here:
https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/HPE-Color-Styles?node-id=277%3A2

**Comment by gregfuruiye** [comment]
New issues have been created to address the findings.
#1106 
#1105 
#1103 (related to #933 )
