### ISSUE TITLE
Title case Form submit buttons and capitalize prepositions if last word in label according to Slack post

### ISSUE THREAD

**Issue by halocline** [hpe-design/design-system#937]
https://hpe.slack.com/archives/C04LMJWQT/p1592949428352700

**Comment by ericsoderberghp** [comment]
Here's the key text from Slack:

The hpe-design-system works with Brand closely to define and advance the experience for our customers. Writing standards contribute to the voice, tone, and grammatical accuracy that inform the experiences we create.
Recently, a question came up about capitalization on forms. When following HPE Writing Style, use title case and capitalize short prepositions when they are the last word in a sentence:

Sign In
Sign Up
Sign Out
