### ISSUE TITLE
Create first pass at List template 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#941]
### Deliverables

- [x] List template page in design system site with a couple of variations and some guidance.
- [x] review with team, in either Slack, GitHub, and/or a meeting
- [ ] publish to the official site with an indicator that it is in progress
- [ ] create new issues for follow-on work

expected to take 1-2 days

Based on Maggies initial designs. 
https://www.figma.com/file/tMYTr17r6hhGajSlNRiPje/HPE-List-Component?node-id=0%3A1
Guidance draft https://github.com/hpe-design/design-system/issues/376#issuecomment-626829288

**Comment by vavalos5** [comment]
Updated Figma file with icon variation for list can be found here: I went ahead and created the icon example on list: https://www.figma.com/file/tMYTr17r6hhGajSlNRiPje/HPE-List-Component?node-id=19%3A135

**Comment by vavalos5** [comment]
List is good to go!

**Comment by ericsoderberghp** [comment]
I have some feedback I will leave on the First pass PR.
