### ISSUE TITLE
Create first pass at Card template 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#942]
### Deliverables

- [x] Card template page in design system site with a couple of variations and some guidance.
- [x] review with team, in either Slack, GitHub, and/or a meeting
- [ ] publish to the official site with an indicator that it is in progress
- [x] create new issues for follow-on work

expected to take 1-2 days

Based on Vickys designs. 
https://www.figma.com/file/je5AYzMavRt1cG7rmw8j1W/HPE-Cards 

We will set up a subsequent meeting to discuss and provide feedback.

**Comment by vavalos5** [comment]
Waiting to get answeres on a few questions. Should be completed by tomorrow or early Wed. (07/01/2020) morning.

**Comment by halocline** [comment]
Closing this "pass" and have created https://github.com/hpe-design/design-system/issues/986 for follow on work.
