### ISSUE TITLE
Add t-shirt sizing within Figma on headings and text

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#957]
"for headings, we have the level (H1, H2, etc) in figma, but we don't have the size (S, M, L, XL).  Ditto for text; we don't have t-shirt sizes, but only point sizes."

**Comment by gregfuruiye** [comment]
T-shirt sizing for heading and text is updated in the Figma Styles Library:

https://www.figma.com/file/oJhw3JqMemtbwWjlLPWW5O/HPE-Typography-Styles?node-id=0%3A1[https://www.figma.com/file/oJhw3JqMemtbwWjlLPWW5O/HPE-Typography-Styles?node-id=0%3A1](url)
