### ISSUE TITLE
Design System Promo Video 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#961]
#883 

Video Direction 
- What is it?
- What is the value? What can it do for me?
- How to engage?

Current Challenges 
- Price 
    - The initial quote came back for 7k-10k. This is 2-3 times higher than we were anticipating. Id like to understand why and if a communication plan was apart of the quote. 
- Underwhelmed with the storyboard
    - The script from the [previous video](https://vimeo.com/214915244) can be used but some terminology would need to be updated. 
    - House of cards implies fragility 
![image](https://user-images.githubusercontent.com/17712467/86648563-35687e80-bf9e-11ea-8c02-9cbd00eb4aca.png)

**Comment by gregfuruiye** [comment]
Here's another shot at some content:

The HPE Design System accelerates your ability to engineer experiences and unleash the full potential of advancing the way people live and work.

A singular design language that contains an open-source library of elements consisting of working code, best practices, design resources, human-centered guidelines, and a vibrant community of contributors. It enables experiences to be crafted with efficiency and uncompromising integrity.

Centered on the customer experience, you’ll have the confidence to create experiences that meet your customers’ needs while ensuring brand consistency and accessibility.

With a dynamic design and developer ecosystem, you have the opportunity to contribute as a critical partner to innovate and evolve our customers’ experience and together, we can be relentless in our pursuit to push the speed at which we can deliver everything as a service with excellence.

**Comment by MikeWalrath** [comment]
Sent the above to the Media Solutions team. We have been approved for the 5k budget. The MS team will be creating a storyboard based on the above draft and will get back to us next week. 

Ill be closing this issue and opening subsequent issues for additional work. 

Thank you @gregfuruiye
