### ISSUE TITLE
Propose plan to align the Design System and Brand Central 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#962]
Mike to come up with a proposal to align content on the Design System site with Brand Central. 

## Design System
- Add tile under Foundation for Brand Central 

**[Philosophy](https://design-system.hpe.design/foundation/philosophy-and-principles)** 
- Add language to align with Brand Strategy 

**[Accessibility](https://design-system.hpe.design/foundation/accessibility)**   
- Copy needed
- Supporting documentation 
- Related articles showing the importance of accessible applications 

**[Our Brand](https://design-system.hpe.design/foundation/our-brand)**  
- Provide brand design assets 
    - Logo (HPE & Aruba) 
    - Favicon 
    - Global header/footer? 
- Copy audit with links to Brand Central 

**[Color](https://design-system.hpe.design/foundation/color)**  
- Update copy in order to clarify usage of light/dark color palette  

**[HPE Images](https://design-system.hpe.design/extend/hpe-images)**
- Copy needed 
- Identify opportunities to guidance (file size, responsiveness, ect...) and examples for photography within the Design System
 
## Brand Central 
**[Icons](https://h10014.www1.hpe.com/brand-central/content/visual-storytelling#iconography)**   
**[Data Visualisation](https://h10014.www1.hpe.com/brand-central/content/visual-storytelling#data-visualization)**  
**[Colors](https://h10014.www1.hpe.com/brand-central/content/color-palette)**  
**[Web and Digital Guidelines](https://h10014.www1.hpe.com/brand-central/content/web-and-digital-guidelines)**
- Update [Digital Design Toolkit](https://h10014.www1.hpe.com/brand-central/content/web-and-digital-guidelines#digital-design-toolkit) 
    - Design Guidance
    - Developer guidance
    - Roadmap? 
    - Evaluate with Brand to see if there are any other assets they would like to add. ie: Forms, Page layouts, etc. 
- Evaluate need for ["Digital Design Gallery"](https://h10014.www1.hpe.com/brand-central/content/web-and-digital-guidelines#digital-design-gallery)

**Comment by krenekj** [comment]
Good start.  Would be good to add links in the description so one can easily navigate to the page and 'see' what is referenced.

Will the design system changes be done in parallel with the roadmap items, or will some things need to be added to the roadmap?

Who owns the Brand Central assets?  Who needs to review/accept the changes?

**Comment by MikeWalrath** [comment]
Thanks @krenekj. I updated the above with links for reference. 

The updates to the will be done in parallel with roadmap items since no particular update mentioned above will be to challenging from a dev/design perspective. There will be time needed for the copy to be written/reviewed but can be done in parallel. If there are any larger updates needed I will add them to the roadmap in order to prioritize and balance work. 

Cassio Cappelossa currently owns the Brand Central site and the assets listed above. Cassio will be retiring in the next 30 days. Id like to discuss with him as well as Tim Harms to understand what can be updated and what the org/ownership process looks like after Cassio retires.

**Comment by MikeWalrath** [comment]
Jeff Askew is the new owner for Brand Central. We met today and we will start the process of updating each site.

**Comment by L0ZZI** [comment]
First proposal here prototype, https://www.figma.com/proto/bPxVZKCep7KlWm3pczayeM/BrandCentral?node-id=1%3A6&viewport=324%2C545%2C0.0625&scaling=scale-down 

and the file, https://www.figma.com/file/bPxVZKCep7KlWm3pczayeM/BrandCentral?node-id=0%3A1
