### ISSUE TITLE
Explore how to create link between docs page and place to edit in Github

### ISSUE THREAD

**Issue by taysea** [hpe-design/design-system#968]
Taking from the MDX discussion, we may want an easier way to go from locating an issue with the site copy to where to fix it in github. For example, MUI has an "Edit this page" button at the top of each page which directs you to that page's file in github. We might try something similar?
<img width="1206" alt="Screen Shot 2020-07-08 at 1 24 21 PM" src="https://user-images.githubusercontent.com/12522275/86966740-843d2200-c11e-11ea-88f4-be78bb7136bb.png">

**Comment by ericsoderberghp** [comment]
Awaiting pull request review + merge.
