### ISSUE TITLE
Investigate Placeholder text color contrast - appears quite a bit lighter in FF than in Safari, Chrome, Edge

### ISSUE THREAD

**Issue by halocline** [hpe-design/design-system#972]
Reported by @jens - Placeholder text color shows up lighter in Firefox than it does in other browsers. Initial inspection shows the color value is correct 'text-weak' which resolves to #BBBBBB or 187, 187, 187. However, to the eye, the color does not seem to have as much contrast in FF.

![Screen Shot 2020-07-09 at 11 56 07 AM](https://user-images.githubusercontent.com/1756948/87074165-b82a4d00-c1db-11ea-91f1-1b2df74acacb.png)
![Screen Shot 2020-07-09 at 12 00 51 PM](https://user-images.githubusercontent.com/1756948/87074273-da23cf80-c1db-11ea-8bff-a03b54b4cf35.png)

**Comment by taysea** [comment]
Have to dig a little more, but apparently Firefox sets an opacity on placeholder text by default.

Resources:
- https://ilikekillnerds.com/2014/10/firefox-placeholder-text-looking-lighter-browsers/
- https://stackoverflow.com/questions/18415765/font-color-of-placeholder-difference-between-firefox-23-0-1-chrome-23-0-1271-64
