### ISSUE TITLE
Remove error color from Next branch  

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#980]
There are two red colors within the Next brand Critical and Error. As Error is not WCAG compliant and to avoid confusion we need to remove the 'error' red.

**Comment by taysea** [comment]
I don't think this issue is relevant any longer. I did a search for `error` color in grommet-theme-hpe and didn't find a match

**Comment by taysea** [comment]
Revising my comment -- `status-error` is coming from base theme. I will set it to undefined for grommet-theme-hpe
