### ISSUE TITLE
Cards template - Create "story line" for the cards template page.

### ISSUE THREAD

**Issue by halocline** [hpe-design/design-system#986]
Story/exploration should consider:
- what is a card
- what are cards' purpose
- what problems do cards solve (use cases)
- what do cards contain
- how can a user interact with a card
- what is a card's behavior
- how are cards presented in a group
- ...

Works in progress:
- Approach 1 (which seems like it is failing to achieve)
  - [PR](https://github.com/hpe-design/design-system/pull/958)
  - [Preview](https://deploy-preview-958--keen-mayer-a86c8b.netlify.app/templates/cards)
- Approach 2 (work in progress, but demonstrates another take)
  - [PR](https://github.com/hpe-design/design-system/pull/982)
  - [Preview](https://deploy-preview-982--keen-mayer-a86c8b.netlify.app/templates/cards)

**Comment by gregfuruiye** [comment]
Throwing this reference to card design here to consider:
[https://medium.com/nextux/8-rules-to-help-you-design-a-better-card-user-interface-a239257d633d](https://medium.com/nextux/8-rules-to-help-you-design-a-better-card-user-interface-a239257d633d)

**Comment by halocline** [comment]
**Problem** 
Intro example --> large body of guidance text --> variants pattern seemed to be falling short
- Unclear what types of variants to produce
- Unclear as to what are the points we want to communicate
- Unclear on the best way to communicate the story as a cohesive whole
- "The whole page is guidance

**Objectives**
- Establish a "story line" we are attempting to tell
  - The what, why, when, and how...
- Does this story line work? Can it apply more broadly?

**Actions**
- Proposal for reworking the page flow --> What, why, when, how flow
  - WHAT - Here is a Card
  - WHY - Here is why it exists and what it consists of (Form and Function) 
  - WHEN - Here are a few use cases and user problems it solves (In context)
  - HOW - Behavior, interaction + variants which demonstrate specifics
- Bring examples in line with guidance (rather than living separately)
- Share [Figma mock](https://www.figma.com/file/IvYbGVlucoUMvUgbYFSG7a/Design-System-Card-Site?node-id=813%3A240)
- Proposal to present Card as a layout component (as opposed to a template)

**Next Steps**
- Code it up
- Does this story line pattern work for other subjects? (Lists and Forms are two immediate candidates)
