### ISSUE TITLE
Alert Icon

### ISSUE THREAD

**Issue by gregfuruiye** [hpe-design/design-system#987]
Exclamation icon for use in field and form validation

[Figma File](https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=2016%3A575)

**Comment by ericsoderberghp** [comment]
I see this in review but I don't see any links to see what to review, moving it back to "In progress"

**Comment by gregfuruiye** [comment]
The latest version in [Figma](https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=2016%3A575)

**Comment by vavalos5** [comment]
Including a screenshot of the icon we're considering for alert icon on form validation.
![Screen Shot 2020-07-24 at 10 33 30 AM](https://user-images.githubusercontent.com/62117454/88571610-c60d0a00-cff2-11ea-90d0-d39c4ba0a88f.png)

**Comment by vavalos5** [comment]
Brittany reached out that she can get the icon to work next to some text. Greg and I to discuss what that final icon will look like today.

**Comment by vavalos5** [comment]
Icon has been created and sent to Shimi to implement in Grommet. Brittany will merge once icon is available.
